main : com.clashwars.essence.Essence
name: Essence
version: 0.1
description: Essentials plugin with lots of commands and utilities.
website: http://placeholder.com
authors: [Worstboy]
softdepend: [Vault]