package com.clashwars.essence.aliases;

import com.clashwars.essence.util.Debug;
import org.bukkit.Material;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Items {

    private static final List<EItem> items = new ArrayList<EItem>();
    private static final HashMap<String, EItem> itemLookup = new HashMap<String, EItem>();

    public static List<EItem> getItems() {
        return items;
    }

    public static EItem getItem(Material material, short data) {
        String key = material.toString().toLowerCase() + "-" + data;
        if (itemLookup.containsKey(key)) {
            return itemLookup.get(key);
        }
        return null;
    }

    public static EItem getItem(String string) {
        string = string.toLowerCase().trim();
        String[] split = string.split(":");
        string = split[0];
        short data = 0;
        if (split.length > 1) {
            try {
                data = Short.parseShort(split[1]);
            } catch (Exception e) {
            }
        }

        EItem match = null;
        for (EItem item : items) {
            if (item.getAliases().contains(string)) {
                match = item;
                break;
            }
        }

        if (match == null) {
            return null;
        }

        EItem dataMatch = getItem(match.getType(), data);
        if (dataMatch == null) {
            return getItem(match.getType(), (short)0);
        }
        return dataMatch;
    }


    static {
        items.add(new EItem("Air", Material.AIR, (short)0, new String[] {}));
        items.add(new EItem("Stone", Material.STONE, (short)0, new String[] {"smoothstone", "rock"}));
        items.add(new EItem("Grass", Material.GRASS, (short)0, new String[] {}));
        items.add(new EItem("Dirt", Material.DIRT, (short)0, new String[] {"earth"}));
        items.add(new EItem("Cobblestone", Material.COBBLESTONE, (short)0, new String[] {"cobble", "cstone"}));
        items.add(new EItem("Oak Plank", Material.WOOD, (short)0, new String[] {"oplank", "woodenplank", "woodplank", "plankwooden", "plankwood", "plankw", "wplank", "oakp"}));
        items.add(new EItem("Spruce Plank", Material.WOOD, (short)1, new String[] {"splank", "sprucep"}));
        items.add(new EItem("Birch Plank", Material.WOOD, (short)2, new String[] {"bplank", "birchp"}));
        items.add(new EItem("Jungle Plank", Material.WOOD, (short)3, new String[] {"jplank", "junglep"}));
        items.add(new EItem("Oak Sapling", Material.SAPLING, (short)0, new String[] {"osapling", "treesapling", "logsapling", "smalltree"}));
        items.add(new EItem("Spruce Sapling", Material.SAPLING, (short)1, new String[] {"ssapling"}));
        items.add(new EItem("Birch Sapling", Material.SAPLING, (short)2, new String[] {"bsapling"}));
        items.add(new EItem("Jungle Sapling", Material.SAPLING, (short)3, new String[] {"jsapling"}));
        items.add(new EItem("Bedrock", Material.BEDROCK, (short)0, new String[] {"adminblock", "oprock", "adminrock", "adminium"}));
        items.add(new EItem("Water", Material.WATER, (short)0, new String[] {"movingwater", "mwater", "flowingwater", "fwater"}));
        items.add(new EItem("Lava", Material.LAVA, (short)0, new String[] {"movinglava", "mlava", "flowinglava", "flava"}));
        items.add(new EItem("Sand", Material.SAND, (short)0, new String[] {}));
        items.add(new EItem("Gold Ore", Material.GOLD_ORE, (short)0, new String[] {"oregold", "gore", "oreg", "goldo"}));
        items.add(new EItem("Iron Ore", Material.IRON_ORE, (short)0, new String[] {"oreiron", "iore", "orei", "irono"}));
        items.add(new EItem("Coal Ore", Material.COAL_ORE, (short)0, new String[] {"orecoal", "core", "orec", "coalo"}));
        items.add(new EItem("Gravel", Material.GRAVEL, (short)0, new String[] {}));
        items.add(new EItem("Oak Log", Material.LOG, (short)0, new String[] {"log", "trunk", "oak", "wood", "oakwood", "olog", "owood"}));
        items.add(new EItem("Spruce Log", Material.LOG, (short)1, new String[] {"sprucewood", "slog", "swood"}));
        items.add(new EItem("Birch Log", Material.LOG, (short)2, new String[] {"birchwood", "blog", "bwood"}));
        items.add(new EItem("Jungle Log", Material.LOG, (short)3, new String[] {"junglewood", "jlog", "jwood"}));
        items.add(new EItem("Leaves Block", Material.LEAVES, (short)0, new String[] {"decayleaf", "decayableleaf", "decayleaves", "decayableleaves", "dleaf", "dleaves"}));
        items.add(new EItem("Spruce Leaves Block", Material.LEAVES, (short)1, new String[] {}));
        items.add(new EItem("Birch Leaves Block", Material.LEAVES, (short)2, new String[] {}));
        items.add(new EItem("Jungle Leaves Block", Material.LEAVES, (short)3, new String[] {}));
        items.add(new EItem("Leaves", Material.LEAVES, (short)4, new String[] {"leaves", "leaf", "oakleaves", "oakleaf", "oleaves", "oleaf"}));
        items.add(new EItem("Spruce Leaves", Material.LEAVES, (short)5, new String[] {"spruceleaves", "spruceleaf", "sleaves", "sleaf"}));
        items.add(new EItem("Birch Leaves", Material.LEAVES, (short)6, new String[] {"birchleaves", "birchleaf", "bleaves", "bleaf"}));
        items.add(new EItem("Jungle Leaves", Material.LEAVES, (short)7, new String[] {"jungleleaves", "jungleleaf", "jleaves", "jleaf"}));
        items.add(new EItem("Sponge", Material.SPONGE, (short)0, new String[] {}));
        items.add(new EItem("Glass", Material.GLASS, (short)0, new String[] {"glassblock", "blockglass"}));
        items.add(new EItem("Lapis Lazuli Ore", Material.LAPIS_ORE, (short)0, new String[] {"lapisore", "lapiso", "lore", "orelapis", "orel", "orelapislazuli"}));
        items.add(new EItem("Lapis Lazuli Block", Material.LAPIS_BLOCK, (short)0, new String[] {"lapisblock", "lblock", "llblock", "blocklapis"}));
        items.add(new EItem("Dispenser", Material.DISPENSER, (short)0, new String[] {"dispense"}));
        items.add(new EItem("Sandstone", Material.SANDSTONE, (short)0, new String[] {"sastone"}));
        items.add(new EItem("Chiseled Sandstone", Material.SANDSTONE, (short)1, new String[] {"chiselsandstone", "chiseledss", "chiselss", "csstone", "creepersandstone", "creepsandstone", "creepersstone"}));
        items.add(new EItem("Smooth Sandstone", Material.SANDSTONE, (short)2, new String[] {"smoothsand", "ssstone", "smoothss"}));
        items.add(new EItem("Note Block", Material.NOTE_BLOCK, (short)0, new String[] {"nblock", "noteb", "note"}));
        items.add(new EItem("Bed Block", Material.BED_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Powered Rail", Material.POWERED_RAIL, (short)0, new String[] {"prail", "prails", "ptrack", "poweredtrack", "boostrail", "boostrails", "boosttrack", "brail", "btrack", "brails"}));
        items.add(new EItem("Detector Rail", Material.DETECTOR_RAIL, (short)0, new String[] {"drail", "drails", "dtrack", "detectortrack"}));
        items.add(new EItem("Sticky Piston", Material.PISTON_STICKY_BASE, (short)0, new String[] {"stickyp", "spiston", "psticky", "pistonsticky"}));
        items.add(new EItem("Web", Material.WEB, (short)0, new String[] {"cobweb", "spiderweb", "cweb", "sweb"}));
        items.add(new EItem("Dead Shrub", Material.LONG_GRASS, (short)0, new String[] {"dshrub", "shrub"}));
        items.add(new EItem("Tall Grass", Material.LONG_GRASS, (short)1, new String[] {"tgrass", "longgrass", "lgrass", "grasstall", "grasst", "grasslong", "grassl"}));
        items.add(new EItem("Fern", Material.LONG_GRASS, (short)2, new String[] {}));
        items.add(new EItem("Piston", Material.PISTON_BASE, (short)0, new String[] {}));
        items.add(new EItem("White Wool", Material.WOOL, (short)0, new String[] {"wool", "cloth", "whitecloth", "whitew"}));
        items.add(new EItem("Orange Wool", Material.WOOL, (short)1, new String[] {"orangecloth", "orangew"}));
        items.add(new EItem("Magenta Wool", Material.WOOL, (short)2, new String[] {"magentacloth", "magentaw"}));
        items.add(new EItem("Light Blue Wool", Material.WOOL, (short)3, new String[] {"lightbluecloth", "lightbluew"}));
        items.add(new EItem("Yellow Wool", Material.WOOL, (short)4, new String[] {"yellowcloth", "yelloww"}));
        items.add(new EItem("Light Green Wool", Material.WOOL, (short)5, new String[] {"greencloth", "greenw", "greenwool"}));
        items.add(new EItem("Pink Wool", Material.WOOL, (short)6, new String[] {"pinkcloth", "pinkw"}));
        items.add(new EItem("Gray Wool", Material.WOOL, (short)7, new String[] {"graycloth", "grayw", "darkgraywool"}));
        items.add(new EItem("Light Gray Wool", Material.WOOL, (short)8, new String[] {"lightgraycloth", "lightgrayw"}));
        items.add(new EItem("Cyan Wool", Material.WOOL, (short)9, new String[] {"cyancloth", "cyanw"}));
        items.add(new EItem("Purple Wool", Material.WOOL, (short)10, new String[] {"purplecloth", "purplew"}));
        items.add(new EItem("Blue Wool", Material.WOOL, (short)11, new String[] {"bluecloth", "bluew"}));
        items.add(new EItem("Brown Wool", Material.WOOL, (short)12, new String[] {"browncloth", "brownw"}));
        items.add(new EItem("Dark Green Wool", Material.WOOL, (short)13, new String[] {"darkgreencloth", "darkgreenw"}));
        items.add(new EItem("Red Wool", Material.WOOL, (short)14, new String[] {"redcloth", "redw"}));
        items.add(new EItem("Black Wool", Material.WOOL, (short)15, new String[] {"blackcloth", "blackw"}));
        items.add(new EItem("Dandelion", Material.YELLOW_FLOWER, (short)0, new String[] {}));
        items.add(new EItem("Brown Mushroom", Material.BROWN_MUSHROOM, (short)0, new String[] {}));
        items.add(new EItem("Red Mushroom", Material.RED_MUSHROOM, (short)0, new String[] {}));
        items.add(new EItem("Gold Block", Material.GOLD_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Iron Block", Material.IRON_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Double Stone Slab", Material.DOUBLE_STEP, (short)0, new String[] {}));
        items.add(new EItem("Double Sandstone Slab", Material.DOUBLE_STEP, (short)1, new String[] {}));
        items.add(new EItem("Double Wooden Slab", Material.DOUBLE_STEP, (short)2, new String[] {}));
        items.add(new EItem("Double Cobblestone Slab", Material.DOUBLE_STEP, (short)3, new String[] {}));
        items.add(new EItem("Double Brick Slab", Material.DOUBLE_STEP, (short)4, new String[] {}));
        items.add(new EItem("Double Stone Brick Slab", Material.DOUBLE_STEP, (short)5, new String[] {}));
        items.add(new EItem("Double Smooth Sandstone Slab", Material.DOUBLE_STEP, (short)9, new String[] {}));
        items.add(new EItem("Stone Slab", Material.STEP, (short)0, new String[] {}));
        items.add(new EItem("Sandstone Slab", Material.STEP, (short)1, new String[] {}));
        items.add(new EItem("Wooden Slab", Material.STEP, (short)2, new String[] {}));
        items.add(new EItem("Cobblestone Slab", Material.STEP, (short)3, new String[] {}));
        items.add(new EItem("Brick Slab", Material.STEP, (short)4, new String[] {}));
        items.add(new EItem("Stone Brick Slab", Material.STEP, (short)5, new String[] {}));
        items.add(new EItem("Brick", Material.BRICK, (short)0, new String[] {}));
        items.add(new EItem("TNT", Material.TNT, (short)0, new String[] {}));
        items.add(new EItem("Bookshelf", Material.BOOKSHELF, (short)0, new String[] {}));
        items.add(new EItem("Moss Stone", Material.MOSSY_COBBLESTONE, (short)0, new String[] {}));
        items.add(new EItem("Obsidian", Material.OBSIDIAN, (short)0, new String[] {}));
        items.add(new EItem("Torch", Material.TORCH, (short)0, new String[] {}));
        items.add(new EItem("Fire", Material.FIRE, (short)0, new String[] {}));
        items.add(new EItem("Monster Spawner", Material.MOB_SPAWNER, (short)0, new String[] {}));
        items.add(new EItem("Oak Wood Stairs", Material.WOOD_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Jungle Wood Stairs", Material.JUNGLE_WOOD_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Spruce Wood Stairs", Material.SPRUCE_WOOD_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Birch Wood Stairs", Material.BIRCH_WOOD_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Chest", Material.CHEST, (short)0, new String[] {}));
        items.add(new EItem("Diamond Ore", Material.DIAMOND_ORE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Block", Material.DIAMOND_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Crafting Table", Material.WORKBENCH, (short)0, new String[] {}));
        items.add(new EItem("Farmland", Material.SOIL, (short)0, new String[] {}));
        items.add(new EItem("Furnace", Material.FURNACE, (short)0, new String[] {}));
        items.add(new EItem("Ladder", Material.LADDER, (short)0, new String[] {}));
        items.add(new EItem("Rails", Material.RAILS, (short)0, new String[] {}));
        items.add(new EItem("Cobblestone Stairs", Material.COBBLESTONE_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Lever", Material.LEVER, (short)0, new String[] {}));
        items.add(new EItem("Stone Pressure Plate", Material.STONE_PLATE, (short)0, new String[] {}));
        items.add(new EItem("Wooden Pressure Plate", Material.WOOD_PLATE, (short)0, new String[] {}));
        items.add(new EItem("Redstone Ore", Material.REDSTONE_ORE, (short)0, new String[] {}));
        items.add(new EItem("Redstone Torch", Material.REDSTONE_TORCH_ON, (short)0, new String[] {}));
        items.add(new EItem("Stone Button", Material.STONE_BUTTON, (short)0, new String[] {}));
        items.add(new EItem("Snow", Material.SNOW, (short)0, new String[] {}));
        items.add(new EItem("Ice", Material.ICE, (short)0, new String[] {}));
        items.add(new EItem("Snow Block", Material.SNOW_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Cactus", Material.CACTUS, (short)0, new String[] {}));
        items.add(new EItem("Clay Block", Material.CLAY, (short)0, new String[] {}));
        items.add(new EItem("Jukebox", Material.JUKEBOX, (short)0, new String[] {}));
        items.add(new EItem("Oak Fence", Material.FENCE, (short)0, new String[] {}));
        items.add(new EItem("Pumpkin", Material.PUMPKIN, (short)0, new String[] {}));
        items.add(new EItem("Netherrack", Material.NETHERRACK, (short)0, new String[] {}));
        items.add(new EItem("Soul Sand", Material.SOUL_SAND, (short)0, new String[] {}));
        items.add(new EItem("Glowstone", Material.GLOWSTONE, (short)0, new String[] {}));
        items.add(new EItem("Portal", Material.PORTAL, (short)0, new String[] {}));
        items.add(new EItem("Jack-O-Lantern", Material.JACK_O_LANTERN, (short)0, new String[] {}));
        items.add(new EItem("Wooden Trapdoor", Material.TRAP_DOOR, (short)0, new String[] {}));
        items.add(new EItem("Stone Monster Egg", Material.MONSTER_EGGS, (short)0, new String[] {}));
        items.add(new EItem("Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)2, new String[] {}));
        items.add(new EItem("Mossy Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)3, new String[] {}));
        items.add(new EItem("Huge Brown Mushroom", Material.HUGE_MUSHROOM_1, (short)0, new String[] {}));
        items.add(new EItem("Huge Red Mushroom", Material.HUGE_MUSHROOM_2, (short)0, new String[] {}));
        items.add(new EItem("Stone Brick", Material.SMOOTH_BRICK, (short)0, new String[] {}));
        items.add(new EItem("Iron Fence", Material.IRON_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Glass Pane", Material.THIN_GLASS, (short)0, new String[] {}));
        items.add(new EItem("Melon Block", Material.MELON_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Mossy Stone Brick", Material.SMOOTH_BRICK, (short)1, new String[] {}));
        items.add(new EItem("Cracked Stone Brick", Material.SMOOTH_BRICK, (short)2, new String[] {}));
        items.add(new EItem("Chiseled Stone Brick", Material.SMOOTH_BRICK, (short)3, new String[] {}));
        items.add(new EItem("Brick Stairs", Material.BRICK_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Fence Gate", Material.FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Vines", Material.VINE, (short)0, new String[] {}));
        items.add(new EItem("Stone Brick Stairs", Material.SMOOTH_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Iron Shovel", Material.IRON_SPADE, (short)0, new String[] {}));
        items.add(new EItem("Iron Pickaxe", Material.IRON_PICKAXE, (short)0, new String[] {}));
        items.add(new EItem("Iron Axe", Material.IRON_AXE, (short)0, new String[] {}));
        items.add(new EItem("Flint and Steel", Material.FLINT_AND_STEEL, (short)0, new String[] {}));
        items.add(new EItem("Apple", Material.APPLE, (short)0, new String[] {}));
        items.add(new EItem("Bow", Material.BOW, (short)0, new String[] {}));
        items.add(new EItem("Arrow", Material.ARROW, (short)0, new String[] {}));
        items.add(new EItem("Coal", Material.COAL, (short)0, new String[] {}));
        items.add(new EItem("Charcoal", Material.COAL, (short)1, new String[] {}));
        items.add(new EItem("Diamond", Material.DIAMOND, (short)0, new String[] {}));
        items.add(new EItem("Iron Ingot", Material.IRON_INGOT, (short)0, new String[] {}));
        items.add(new EItem("Gold Ingot", Material.GOLD_INGOT, (short)0, new String[] {}));
        items.add(new EItem("Iron Sword", Material.IRON_SWORD, (short)0, new String[] {}));
        items.add(new EItem("Wooden Sword", Material.WOOD_SWORD, (short)0, new String[] {}));
        items.add(new EItem("Wooden Shovel", Material.WOOD_SPADE, (short)0, new String[] {}));
        items.add(new EItem("Wooden Pickaxe", Material.WOOD_PICKAXE, (short)0, new String[] {}));
        items.add(new EItem("Wooden Axe", Material.WOOD_AXE, (short)0, new String[] {}));
        items.add(new EItem("Stone Sword", Material.STONE_SWORD, (short)0, new String[] {}));
        items.add(new EItem("Stone Shovel", Material.STONE_SPADE, (short)0, new String[] {}));
        items.add(new EItem("Stone Pickaxe", Material.STONE_PICKAXE, (short)0, new String[] {}));
        items.add(new EItem("Stone Axe", Material.STONE_AXE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Sword", Material.DIAMOND_SWORD, (short)0, new String[] {}));
        items.add(new EItem("Diamond Shovel", Material.DIAMOND_SPADE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Pickaxe", Material.DIAMOND_PICKAXE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Axe", Material.DIAMOND_AXE, (short)0, new String[] {}));
        items.add(new EItem("Stick", Material.STICK, (short)0, new String[] {}));
        items.add(new EItem("Bowl", Material.BOWL, (short)0, new String[] {}));
        items.add(new EItem("Mushroom Soup", Material.MUSHROOM_SOUP, (short)0, new String[] {}));
        items.add(new EItem("Gold Sword", Material.GOLD_SWORD, (short)0, new String[] {}));
        items.add(new EItem("Gold Shovel", Material.GOLD_SPADE, (short)0, new String[] {}));
        items.add(new EItem("Gold Pickaxe", Material.GOLD_PICKAXE, (short)0, new String[] {}));
        items.add(new EItem("Gold Axe", Material.GOLD_AXE, (short)0, new String[] {}));
        items.add(new EItem("String", Material.STRING, (short)0, new String[] {}));
        items.add(new EItem("Feather", Material.FEATHER, (short)0, new String[] {}));
        items.add(new EItem("Gunpowder", Material.SULPHUR, (short)0, new String[] {}));
        items.add(new EItem("Wooden Hoe", Material.WOOD_HOE, (short)0, new String[] {}));
        items.add(new EItem("Stone Hoe", Material.STONE_HOE, (short)0, new String[] {}));
        items.add(new EItem("Iron Hoe", Material.IRON_HOE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Hoe", Material.DIAMOND_HOE, (short)0, new String[] {}));
        items.add(new EItem("Gold Hoe", Material.GOLD_HOE, (short)0, new String[] {}));
        items.add(new EItem("Seeds", Material.SEEDS, (short)0, new String[] {}));
        items.add(new EItem("Wheat", Material.WHEAT, (short)0, new String[] {}));
        items.add(new EItem("Bread", Material.BREAD, (short)0, new String[] {}));
        items.add(new EItem("Leather Cap", Material.LEATHER_HELMET, (short)0, new String[] {}));
        items.add(new EItem("Leather Tunic", Material.LEATHER_CHESTPLATE, (short)0, new String[] {}));
        items.add(new EItem("Leather Pants", Material.LEATHER_LEGGINGS, (short)0, new String[] {}));
        items.add(new EItem("Leather Boots", Material.LEATHER_BOOTS, (short)0, new String[] {}));
        items.add(new EItem("Chainmail Helmet", Material.CHAINMAIL_HELMET, (short)0, new String[] {}));
        items.add(new EItem("Chainmail Chestplate", Material.CHAINMAIL_CHESTPLATE, (short)0, new String[] {}));
        items.add(new EItem("Chainmail Leggings", Material.CHAINMAIL_LEGGINGS, (short)0, new String[] {}));
        items.add(new EItem("Chainmail Boots", Material.CHAINMAIL_BOOTS, (short)0, new String[] {}));
        items.add(new EItem("Iron Helmet", Material.IRON_HELMET, (short)0, new String[] {}));
        items.add(new EItem("Iron Chestplate", Material.IRON_CHESTPLATE, (short)0, new String[] {}));
        items.add(new EItem("Iron Leggings", Material.IRON_LEGGINGS, (short)0, new String[] {}));
        items.add(new EItem("Iron Boots", Material.IRON_BOOTS, (short)0, new String[] {}));
        items.add(new EItem("Diamond Helmet", Material.DIAMOND_HELMET, (short)0, new String[] {}));
        items.add(new EItem("Diamond Chestplate", Material.DIAMOND_CHESTPLATE, (short)0, new String[] {}));
        items.add(new EItem("Diamond Leggings", Material.DIAMOND_LEGGINGS, (short)0, new String[] {}));
        items.add(new EItem("Diamond Boots", Material.DIAMOND_BOOTS, (short)0, new String[] {}));
        items.add(new EItem("Gold Helmet", Material.GOLD_HELMET, (short)0, new String[] {}));
        items.add(new EItem("Gold Chestplate", Material.GOLD_CHESTPLATE, (short)0, new String[] {}));
        items.add(new EItem("Gold Leggings", Material.GOLD_LEGGINGS, (short)0, new String[] {}));
        items.add(new EItem("Gold Boots", Material.GOLD_BOOTS, (short)0, new String[] {}));
        items.add(new EItem("Flint", Material.FLINT, (short)0, new String[] {}));
        items.add(new EItem("Raw Porkchop", Material.PORK, (short)0, new String[] {}));
        items.add(new EItem("Cooked Porkchop", Material.GRILLED_PORK, (short)0, new String[] {}));
        items.add(new EItem("Paintings", Material.PAINTING, (short)0, new String[] {}));
        items.add(new EItem("Golden Apple", Material.GOLDEN_APPLE, (short)0, new String[] {}));
        items.add(new EItem("Enchanted Golden Apple", Material.GOLDEN_APPLE, (short)1, new String[] {}));
        items.add(new EItem("Sign", Material.SIGN, (short)0, new String[] {}));
        items.add(new EItem("Wooden Door", Material.WOOD_DOOR, (short)0, new String[] {}));
        items.add(new EItem("Bucket", Material.BUCKET, (short)0, new String[] {}));
        items.add(new EItem("Water Bucket", Material.WATER_BUCKET, (short)0, new String[] {}));
        items.add(new EItem("Lava Bucket", Material.LAVA_BUCKET, (short)0, new String[] {}));
        items.add(new EItem("Minecart", Material.MINECART, (short)0, new String[] {}));
        items.add(new EItem("Saddle", Material.SADDLE, (short)0, new String[] {}));
        items.add(new EItem("Iron Door", Material.IRON_DOOR, (short)0, new String[] {}));
        items.add(new EItem("Redstone Dust", Material.REDSTONE, (short)0, new String[] {}));
        items.add(new EItem("Snowball", Material.SNOW_BALL, (short)0, new String[] {}));
        items.add(new EItem("Boat", Material.BOAT, (short)0, new String[] {}));
        items.add(new EItem("Leather", Material.LEATHER, (short)0, new String[] {}));
        items.add(new EItem("Milk Bucket", Material.MILK_BUCKET, (short)0, new String[] {}));
        items.add(new EItem("Clay Brick", Material.CLAY_BRICK, (short)0, new String[] {}));
        items.add(new EItem("Clay", Material.CLAY_BALL, (short)0, new String[] {}));
        items.add(new EItem("Sugar Cane", Material.SUGAR_CANE, (short)0, new String[] {}));
        items.add(new EItem("Paper", Material.PAPER, (short)0, new String[] {}));
        items.add(new EItem("Book", Material.BOOK, (short)0, new String[] {}));
        items.add(new EItem("Slimeball", Material.SLIME_BALL, (short)0, new String[] {}));
        items.add(new EItem("Storage Minecart", Material.STORAGE_MINECART, (short)0, new String[] {}));
        items.add(new EItem("Powered Minecart", Material.POWERED_MINECART, (short)0, new String[] {}));
        items.add(new EItem("Egg", Material.EGG, (short)0, new String[] {}));
        items.add(new EItem("Compass", Material.COMPASS, (short)0, new String[] {}));
        items.add(new EItem("Fishing Rod", Material.FISHING_ROD, (short)0, new String[] {}));
        items.add(new EItem("Clock", Material.WATCH, (short)0, new String[] {}));
        items.add(new EItem("Glowstone Dust", Material.GLOWSTONE_DUST, (short)0, new String[] {}));
        items.add(new EItem("Raw Fish", Material.RAW_FISH, (short)0, new String[] {}));
        items.add(new EItem("Cooked Fish", Material.COOKED_FISH, (short)0, new String[] {}));
        items.add(new EItem("Ink Sac", Material.INK_SACK, (short)0, new String[] {}));
        items.add(new EItem("Red Dye", Material.INK_SACK, (short)1, new String[] {}));
        items.add(new EItem("Cactus Green", Material.INK_SACK, (short)2, new String[] {}));
        items.add(new EItem("Cocoa Beans", Material.INK_SACK, (short)3, new String[] {}));
        items.add(new EItem("Lapis Lazuli", Material.INK_SACK, (short)4, new String[] {}));
        items.add(new EItem("Purple Dye", Material.INK_SACK, (short)5, new String[] {}));
        items.add(new EItem("Cyan Dye", Material.INK_SACK, (short)6, new String[] {}));
        items.add(new EItem("Light Gray Dye", Material.INK_SACK, (short)7, new String[] {}));
        items.add(new EItem("Gray Dye", Material.INK_SACK, (short)8, new String[] {}));
        items.add(new EItem("Pink Dye", Material.INK_SACK, (short)9, new String[] {}));
        items.add(new EItem("Lime Dye", Material.INK_SACK, (short)10, new String[] {}));
        items.add(new EItem("Dandelion Yellow", Material.INK_SACK, (short)11, new String[] {}));
        items.add(new EItem("Light Blue Dye", Material.INK_SACK, (short)12, new String[] {}));
        items.add(new EItem("Magenta Dye", Material.INK_SACK, (short)13, new String[] {}));
        items.add(new EItem("Orange Dye", Material.INK_SACK, (short)14, new String[] {}));
        items.add(new EItem("Bone Meal", Material.INK_SACK, (short)15, new String[] {}));
        items.add(new EItem("Bone", Material.BONE, (short)0, new String[] {}));
        items.add(new EItem("Sugar", Material.SUGAR, (short)0, new String[] {}));
        items.add(new EItem("Cake", Material.CAKE, (short)0, new String[] {}));
        items.add(new EItem("Melon Slice", Material.MELON, (short)0, new String[] {}));
        items.add(new EItem("Pumpkin Seed", Material.PUMPKIN_SEEDS, (short)0, new String[] {}));
        items.add(new EItem("Melon Seed", Material.MELON_SEEDS, (short)0, new String[] {}));
        items.add(new EItem("Raw Beef", Material.RAW_BEEF, (short)0, new String[] {}));
        items.add(new EItem("Steak", Material.COOKED_BEEF, (short)0, new String[] {}));
        items.add(new EItem("Raw Chicken", Material.RAW_CHICKEN, (short)0, new String[] {}));
        items.add(new EItem("Cooked Chicken", Material.COOKED_CHICKEN, (short)0, new String[] {}));
        items.add(new EItem("Rotten Flesh", Material.ROTTEN_FLESH, (short)0, new String[] {}));
        items.add(new EItem("Bed", Material.BED, (short)0, new String[] {}));
        items.add(new EItem("Redstone Repeater", Material.DIODE, (short)0, new String[] {}));
        items.add(new EItem("Cookie", Material.COOKIE, (short)0, new String[] {}));
        items.add(new EItem("Map", Material.MAP, (short)0, new String[] {}));
        items.add(new EItem("Empty Map", Material.EMPTY_MAP, (short)0, new String[] {}));
        items.add(new EItem("Shears", Material.SHEARS, (short)0, new String[] {}));
        items.add(new EItem("Ender Pearl", Material.ENDER_PEARL, (short)0, new String[] {}));
        items.add(new EItem("Mycelium", Material.MYCEL, (short)0, new String[] {}));
        items.add(new EItem("Lily Pad", Material.WATER_LILY, (short)0, new String[] {}));
        items.add(new EItem("Cauldron Block", Material.CAULDRON, (short)0, new String[] {}));
        items.add(new EItem("Cauldron", Material.CAULDRON_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Enchantment Table", Material.ENCHANTMENT_TABLE, (short)0, new String[] {}));
        items.add(new EItem("Brewing Stand Block", Material.BREWING_STAND, (short)0, new String[] {}));
        items.add(new EItem("Brewing Stand", Material.BREWING_STAND_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Nether Brick", Material.NETHER_BRICK, (short)0, new String[] {}));
        items.add(new EItem("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Nether Brick Fence", Material.NETHER_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Netherwarts", Material.NETHER_WARTS, (short)0, new String[] {}));
        items.add(new EItem("Netherstalk", Material.NETHER_STALK, (short)0, new String[] {}));
        items.add(new EItem("End Portal", Material.ENDER_PORTAL, (short)0, new String[] {}));
        items.add(new EItem("End Portal Frame", Material.ENDER_PORTAL_FRAME, (short)0, new String[] {}));
        items.add(new EItem("End Stone", Material.ENDER_STONE, (short)0, new String[] {}));
        items.add(new EItem("Dragon Egg", Material.DRAGON_EGG, (short)0, new String[] {}));
        items.add(new EItem("Blaze Rod", Material.BLAZE_ROD, (short)0, new String[] {}));
        items.add(new EItem("Ghast Tear", Material.GHAST_TEAR, (short)0, new String[] {}));
        items.add(new EItem("Gold Nugget", Material.GOLD_NUGGET, (short)0, new String[] {}));
        items.add(new EItem("Glass Bottle", Material.GLASS_BOTTLE, (short)0, new String[] {}));
        items.add(new EItem("Potion", Material.POTION, (short)0, new String[] {}));
        items.add(new EItem("Water Bottle", Material.POTION, (short)0, new String[] {}));
        items.add(new EItem("Awkward Potion", Material.POTION, (short)16, new String[] {}));
        items.add(new EItem("Thick Potion", Material.POTION, (short)32, new String[] {}));
        items.add(new EItem("Mundane Potion (Extended);", Material.POTION, (short)64, new String[] {}));
        items.add(new EItem("Mundane Potion", Material.POTION, (short)8192, new String[] {}));
        items.add(new EItem("Potion of Regeneration", Material.POTION, (short)8193, new String[] {}));
        items.add(new EItem("Potion of Regeneration (Extended);", Material.POTION, (short)8257, new String[] {}));
        items.add(new EItem("Potion of Regeneration II", Material.POTION, (short)8225, new String[] {}));
        items.add(new EItem("Potion of Swiftness", Material.POTION, (short)8194, new String[] {}));
        items.add(new EItem("Potion of Swiftness (Extended);", Material.POTION, (short)8258, new String[] {}));
        items.add(new EItem("Potion of Swiftness II", Material.POTION, (short)8226, new String[] {}));
        items.add(new EItem("Potion of Fire Resistance", Material.POTION, (short)8195, new String[] {}));
        items.add(new EItem("Potion of Fire Resistance (Extended);", Material.POTION, (short)8259, new String[] {}));
        items.add(new EItem("Potion of Fire Resistance (Reverted);", Material.POTION, (short)8227, new String[] {}));
        items.add(new EItem("Potion of Healing", Material.POTION, (short)8197, new String[] {}));
        items.add(new EItem("Potion of Healing (Reverted);", Material.POTION, (short)8261, new String[] {}));
        items.add(new EItem("Potion of Healing II", Material.POTION, (short)8229, new String[] {}));
        items.add(new EItem("Potion of Strength", Material.POTION, (short)8201, new String[] {}));
        items.add(new EItem("Potion of Strength (Extended);", Material.POTION, (short)8265, new String[] {}));
        items.add(new EItem("Potion of Strength II", Material.POTION, (short)8233, new String[] {}));
        items.add(new EItem("Potion of Poison", Material.POTION, (short)8196, new String[] {}));
        items.add(new EItem("Potion of Poison (Extended);", Material.POTION, (short)8260, new String[] {}));
        items.add(new EItem("Potion of Poison II", Material.POTION, (short)8228, new String[] {}));
        items.add(new EItem("Potion of Weakness", Material.POTION, (short)8200, new String[] {}));
        items.add(new EItem("Potion of Weakness (Extended);", Material.POTION, (short)8264, new String[] {}));
        items.add(new EItem("Potion of Weakness (Reverted);", Material.POTION, (short)8232, new String[] {}));
        items.add(new EItem("Potion of Slowness", Material.POTION, (short)8202, new String[] {}));
        items.add(new EItem("Potion of Slowness (Extended);", Material.POTION, (short)8266, new String[] {}));
        items.add(new EItem("Potion of Slowness (Reverted);", Material.POTION, (short)8234, new String[] {}));
        items.add(new EItem("Potion of Harming", Material.POTION, (short)8204, new String[] {}));
        items.add(new EItem("Potion of Harming (Reverted);", Material.POTION, (short)8268, new String[] {}));
        items.add(new EItem("Potion of Harming II", Material.POTION, (short)8236, new String[] {}));
        items.add(new EItem("Splash Mundane Potion", Material.POTION, (short)16384, new String[] {}));
        items.add(new EItem("Splash Potion of Regeneration", Material.POTION, (short)16385, new String[] {}));
        items.add(new EItem("Splash Potion of Regeneration (Extended);", Material.POTION, (short)16449, new String[] {}));
        items.add(new EItem("Splash Potion of Regeneration II", Material.POTION, (short)16417, new String[] {}));
        items.add(new EItem("Splash Potion of Swiftness", Material.POTION, (short)16386, new String[] {}));
        items.add(new EItem("Splash Potion of Swiftness (Extended);", Material.POTION, (short)16450, new String[] {}));
        items.add(new EItem("Splash Potion of Swiftness II", Material.POTION, (short)16418, new String[] {}));
        items.add(new EItem("Splash Potion of Fire Resistance", Material.POTION, (short)16387, new String[] {}));
        items.add(new EItem("Splash Potion of Fire Resistance (Extended);", Material.POTION, (short)16451, new String[] {}));
        items.add(new EItem("Splash Potion of Fire Resistance (Reverted);", Material.POTION, (short)16419, new String[] {}));
        items.add(new EItem("Splash Potion of Healing", Material.POTION, (short)16389, new String[] {}));
        items.add(new EItem("Splash Potion of Healing (Reverted);", Material.POTION, (short)16453, new String[] {}));
        items.add(new EItem("Splash Potion of Healing II", Material.POTION, (short)16421, new String[] {}));
        items.add(new EItem("Splash Potion of Strength", Material.POTION, (short)16393, new String[] {}));
        items.add(new EItem("Splash Potion of Strength (Extended);", Material.POTION, (short)16457, new String[] {}));
        items.add(new EItem("Splash Potion of Strength II", Material.POTION, (short)16425, new String[] {}));
        items.add(new EItem("Splash Potion of Poison", Material.POTION, (short)16388, new String[] {}));
        items.add(new EItem("Splash Potion of Poison (Extended);", Material.POTION, (short)16452, new String[] {}));
        items.add(new EItem("Splash Potion of Poison II", Material.POTION, (short)16420, new String[] {}));
        items.add(new EItem("Splash Potion of Weakness", Material.POTION, (short)16392, new String[] {}));
        items.add(new EItem("Splash Potion of Weakness (Extended);", Material.POTION, (short)16456, new String[] {}));
        items.add(new EItem("Splash Potion of Weakness (Reverted);", Material.POTION, (short)16424, new String[] {}));
        items.add(new EItem("Splash Potion of Slowness", Material.POTION, (short)16394, new String[] {}));
        items.add(new EItem("Splash Potion of Slowness (Extended);", Material.POTION, (short)16458, new String[] {}));
        items.add(new EItem("Splash Potion of Slowness (Reverted);", Material.POTION, (short)16426, new String[] {}));
        items.add(new EItem("Splash Potion of Harming", Material.POTION, (short)16396, new String[] {}));
        items.add(new EItem("Splash Potion of Harming (Reverted);", Material.POTION, (short)16460, new String[] {}));
        items.add(new EItem("Splash Potion of Harming II", Material.POTION, (short)16428, new String[] {}));
        items.add(new EItem("Spider Eye", Material.SPIDER_EYE, (short)0, new String[] {}));
        items.add(new EItem("Fermented Spider Eye", Material.FERMENTED_SPIDER_EYE, (short)0, new String[] {}));
        items.add(new EItem("Blaze Powder", Material.BLAZE_POWDER, (short)0, new String[] {}));
        items.add(new EItem("Magma Cream", Material.MAGMA_CREAM, (short)0, new String[] {}));
        items.add(new EItem("Eye of Ender", Material.EYE_OF_ENDER, (short)0, new String[] {}));
        items.add(new EItem("Glistering Melon", Material.SPECKLED_MELON, (short)0, new String[] {}));
        items.add(new EItem("Spawn Egg", Material.MONSTER_EGG, (short)0, new String[] {}));
        items.add(new EItem("Creeper Spawn Egg", Material.MONSTER_EGG, (short)50, new String[] {}));
        items.add(new EItem("Skeleton Spawn Egg", Material.MONSTER_EGG, (short)51, new String[] {}));
        items.add(new EItem("Spider Spawn Egg", Material.MONSTER_EGG, (short)52, new String[] {}));
        items.add(new EItem("Zombie Spawn Egg", Material.MONSTER_EGG, (short)54, new String[] {}));
        items.add(new EItem("Slime Spawn Egg", Material.MONSTER_EGG, (short)55, new String[] {}));
        items.add(new EItem("Ghast Spawn Egg", Material.MONSTER_EGG, (short)56, new String[] {}));
        items.add(new EItem("Zombie Pigman Spawn Egg", Material.MONSTER_EGG, (short)57, new String[] {}));
        items.add(new EItem("Enderman Spawn Egg", Material.MONSTER_EGG, (short)58, new String[] {}));
        items.add(new EItem("Cave Spider Spawn Egg", Material.MONSTER_EGG, (short)59, new String[] {}));
        items.add(new EItem("Silverfish Spawn Egg", Material.MONSTER_EGG, (short)60, new String[] {}));
        items.add(new EItem("Blaze Spawn Egg", Material.MONSTER_EGG, (short)61, new String[] {}));
        items.add(new EItem("Magma Cube Spawn Egg", Material.MONSTER_EGG, (short)62, new String[] {}));
        items.add(new EItem("Pig Spawn Egg", Material.MONSTER_EGG, (short)90, new String[] {}));
        items.add(new EItem("Sheep Spawn Egg", Material.MONSTER_EGG, (short)91, new String[] {}));
        items.add(new EItem("Cow Spawn Egg", Material.MONSTER_EGG, (short)92, new String[] {}));
        items.add(new EItem("Chicken Spawn Egg", Material.MONSTER_EGG, (short)93, new String[] {}));
        items.add(new EItem("Squid Spawn Egg", Material.MONSTER_EGG, (short)94, new String[] {}));
        items.add(new EItem("Wolf Spawn Egg", Material.MONSTER_EGG, (short)95, new String[] {}));
        items.add(new EItem("Mooshroom Spawn Egg", Material.MONSTER_EGG, (short)96, new String[] {}));
        items.add(new EItem("Ocelot Spawn Egg", Material.MONSTER_EGG, (short)98, new String[] {}));
        items.add(new EItem("Villager Spawn Egg", Material.MONSTER_EGG, (short)120, new String[] {}));
        items.add(new EItem("Bottle 'o Enchanting", Material.EXP_BOTTLE, (short)0, new String[] {}));
        items.add(new EItem("Fire Charge", Material.FIREBALL, (short)0, new String[] {}));
        items.add(new EItem("13 Disc", Material.GOLD_RECORD, (short)0, new String[] {}));
        items.add(new EItem("cat Disc", Material.GREEN_RECORD, (short)0, new String[] {}));
        items.add(new EItem("blocks Disc", Material.RECORD_3, (short)0, new String[] {}));
        items.add(new EItem("chirp Disc", Material.RECORD_4, (short)0, new String[] {}));
        items.add(new EItem("far Disc", Material.RECORD_5, (short)0, new String[] {}));
        items.add(new EItem("mall Disc", Material.RECORD_6, (short)0, new String[] {}));
        items.add(new EItem("mellohi Disc", Material.RECORD_7, (short)0, new String[] {}));
        items.add(new EItem("stahl Disc", Material.RECORD_8, (short)0, new String[] {}));
        items.add(new EItem("strad Disc", Material.RECORD_9, (short)0, new String[] {}));
        items.add(new EItem("ward Disc", Material.RECORD_10, (short)0, new String[] {}));
        items.add(new EItem("11 Disc", Material.RECORD_11, (short)0, new String[] {}));
        items.add(new EItem("wait Disc", Material.RECORD_12, (short)0, new String[] {}));
        items.add(new EItem("Redstone Lamp", Material.REDSTONE_LAMP_OFF, (short)0, new String[] {}));
        items.add(new EItem("Redstone Torch Off", Material.REDSTONE_TORCH_OFF, (short)0, new String[] {}));
        items.add(new EItem("Emerald Ore", Material.EMERALD_ORE, (short)0, new String[] {}));
        items.add(new EItem("Emerald", Material.EMERALD, (short)0, new String[] {}));
        items.add(new EItem("Emerald Block", Material.EMERALD_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Ender Chest", Material.ENDER_CHEST, (short)0, new String[] {}));
        items.add(new EItem("Tripwire Hook", Material.TRIPWIRE_HOOK, (short)0, new String[] {}));
        items.add(new EItem("Tripwire", Material.TRIPWIRE, (short)0, new String[] {}));
        items.add(new EItem("Sandstone Stair", Material.SANDSTONE_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Double Oak Slab", Material.WOOD_DOUBLE_STEP, (short)0, new String[] {}));
        items.add(new EItem("Double Spruce Slab", Material.WOOD_DOUBLE_STEP, (short)1, new String[] {}));
        items.add(new EItem("Double Birch Slab", Material.WOOD_DOUBLE_STEP, (short)2, new String[] {}));
        items.add(new EItem("Double Jungle Wood Slab", Material.WOOD_DOUBLE_STEP, (short)3, new String[] {}));
        items.add(new EItem("Oak Slab", Material.WOOD_STEP, (short)0, new String[] {}));
        items.add(new EItem("Spruce Slab", Material.WOOD_STEP, (short)1, new String[] {}));
        items.add(new EItem("Birch Slab", Material.WOOD_STEP, (short)2, new String[] {}));
        items.add(new EItem("Jungle Wood Slab", Material.WOOD_STEP, (short)3, new String[] {}));
        items.add(new EItem("Book and Quill", Material.BOOK_AND_QUILL, (short)0, new String[] {}));
        items.add(new EItem("Written Book", Material.WRITTEN_BOOK, (short)0, new String[] {}));
        items.add(new EItem("Cocoa Pod", Material.COCOA, (short)0, new String[] {}));
        items.add(new EItem("Command Block", Material.COMMAND, (short)0, new String[] {}));
        items.add(new EItem("Beacon Block", Material.BEACON, (short)0, new String[] {}));
        items.add(new EItem("Anvil", Material.ANVIL, (short)0, new String[] {}));
        items.add(new EItem("Slightly Damaged Anvil", Material.ANVIL, (short)1, new String[] {}));
        items.add(new EItem("Very Damaged Anvil", Material.ANVIL, (short)2, new String[] {}));
        items.add(new EItem("Flower Pot Block", Material.FLOWER_POT, (short)0, new String[] {}));
        items.add(new EItem("Flower Pot", Material.FLOWER_POT_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Cobblestone Wall", Material.COBBLE_WALL, (short)0, new String[] {}));
        items.add(new EItem("Mossy Cobblestone Wall", Material.COBBLE_WALL, (short)1, new String[] {}));
        items.add(new EItem("Item Frame", Material.ITEM_FRAME, (short)0, new String[] {}));
        items.add(new EItem("Skeleton Skull", Material.SKULL_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Wither Skeleton Skull", Material.SKULL_ITEM, (short)1, new String[] {}));
        items.add(new EItem("Zombie Head", Material.SKULL_ITEM, (short)2, new String[] {}));
        items.add(new EItem("Human Head", Material.SKULL_ITEM, (short)3, new String[] {}));
        items.add(new EItem("Creeper Head", Material.SKULL_ITEM, (short)4, new String[] {}));
        items.add(new EItem("Carrot", Material.CARROT_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Golden Carrot", Material.GOLDEN_CARROT, (short)0, new String[] {}));
        items.add(new EItem("Carrot Block", Material.CARROT, (short)0, new String[] {}));
        items.add(new EItem("Carrot on a Stick", Material.CARROT_STICK, (short)0, new String[] {}));
        items.add(new EItem("Potato", Material.POTATO_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Potato Block", Material.POTATO, (short)0, new String[] {}));
        items.add(new EItem("Baked Potato", Material.BAKED_POTATO, (short)0, new String[] {}));
        items.add(new EItem("Poisonous Potato", Material.POISONOUS_POTATO, (short)0, new String[] {}));
        items.add(new EItem("Wood Button", Material.WOOD_BUTTON, (short)0, new String[] {}));
        items.add(new EItem("Pumpkin Pie", Material.PUMPKIN_PIE, (short)0, new String[] {}));
        items.add(new EItem("Potion of Invisibility", Material.POTION, (short)8206, new String[] {}));
        items.add(new EItem("Potion of Invisibility (Extended);", Material.POTION, (short)8270, new String[] {}));
        items.add(new EItem("Potion of Night Vision", Material.POTION, (short)8198, new String[] {}));
        items.add(new EItem("Potion of Night Vision (Extended);", Material.POTION, (short)8262, new String[] {}));
        items.add(new EItem("Enchanted Book", Material.ENCHANTED_BOOK, (short)0, new String[] {}));
        items.add(new EItem("Nether Star", Material.NETHER_STAR, (short)0, new String[] {}));
        items.add(new EItem("Firework Star", Material.FIREWORK_CHARGE, (short)0, new String[] {}));
        items.add(new EItem("Firework Rocket", Material.FIREWORK, (short)0, new String[] {}));
        items.add(new EItem("White Firework Star", Material.FIREWORK_CHARGE, (short)1, new String[] {}));
        items.add(new EItem("Orange Firework Star", Material.FIREWORK_CHARGE, (short)2, new String[] {}));
        items.add(new EItem("Magenta Firework Star", Material.FIREWORK_CHARGE, (short)3, new String[] {}));
        items.add(new EItem("Light Blue Firework Star", Material.FIREWORK_CHARGE, (short)4, new String[] {}));
        items.add(new EItem("Yellow Firework Star", Material.FIREWORK_CHARGE, (short)5, new String[] {}));
        items.add(new EItem("Lime Firework Star", Material.FIREWORK_CHARGE, (short)6, new String[] {}));
        items.add(new EItem("Pink Firework Star", Material.FIREWORK_CHARGE, (short)7, new String[] {}));
        items.add(new EItem("Gray Firework Star", Material.FIREWORK_CHARGE, (short)8, new String[] {}));
        items.add(new EItem("Light Gray Firework Star", Material.FIREWORK_CHARGE, (short)9, new String[] {}));
        items.add(new EItem("Cyan Firework Star", Material.FIREWORK_CHARGE, (short)10, new String[] {}));
        items.add(new EItem("Purple Firework Star", Material.FIREWORK_CHARGE, (short)11, new String[] {}));
        items.add(new EItem("Blue Firework Star", Material.FIREWORK_CHARGE, (short)12, new String[] {}));
        items.add(new EItem("Brown Firework Star", Material.FIREWORK_CHARGE, (short)13, new String[] {}));
        items.add(new EItem("Green Firework Star", Material.FIREWORK_CHARGE, (short)14, new String[] {}));
        items.add(new EItem("Red Firework Star", Material.FIREWORK_CHARGE, (short)15, new String[] {}));
        items.add(new EItem("Black Firework Star", Material.FIREWORK_CHARGE, (short)16, new String[] {}));
        items.add(new EItem("Dead Bush", Material.DEAD_BUSH, (short)0, new String[] {"deadbush", "dbush", "bush"}));
        items.add(new EItem("Nether Brick Slab", Material.STEP, (short)6, new String[] {}));
        items.add(new EItem("Activator Rail", Material.ACTIVATOR_RAIL, (short)0, new String[] {}));
        items.add(new EItem("Block of Redstone", Material.REDSTONE_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Daylight Sensor", Material.DAYLIGHT_DETECTOR, (short)0, new String[] {}));
        items.add(new EItem("Dropper", Material.DROPPER, (short)0, new String[] {}));
        items.add(new EItem("Hopper", Material.HOPPER, (short)0, new String[] {}));
        items.add(new EItem("Explosive Minecart", Material.EXPLOSIVE_MINECART, (short)0, new String[] {}));
        items.add(new EItem("Hopper Minecart", Material.HOPPER_MINECART, (short)0, new String[] {}));
        items.add(new EItem("Redstone Comparator", Material.REDSTONE_COMPARATOR, (short)0, new String[] {}));
        items.add(new EItem("Trapped Chest", Material.TRAPPED_CHEST, (short)0, new String[] {}));
        items.add(new EItem("Nether Brick Item", Material.NETHER_BRICK_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Nether Quartz", Material.QUARTZ, (short)0, new String[] {}));
        items.add(new EItem("Nether Quartz Ore", Material.QUARTZ_ORE, (short)0, new String[] {}));
        items.add(new EItem("Quartz Block", Material.QUARTZ_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Quartz Slab", Material.STEP, (short)7, new String[] {}));
        items.add(new EItem("Quartz Double Slab", Material.DOUBLE_STEP, (short)7, new String[] {}));
        items.add(new EItem("Quartz Stairs", Material.QUARTZ_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Chiseled Quartz", Material.QUARTZ_BLOCK, (short)1, new String[] {}));
        items.add(new EItem("Quartz Pillar", Material.QUARTZ_BLOCK, (short)2, new String[] {}));
        items.add(new EItem("Weighted Gold Plate", Material.GOLD_PLATE, (short)0, new String[] {}));
        items.add(new EItem("Weighted Iron Plate", Material.IRON_PLATE, (short)0, new String[] {}));
        items.add(new EItem("Horse Spawn Egg", Material.MONSTER_EGG, (short)100, new String[] {}));
        items.add(new EItem("Diamond Horse Armor", Material.DIAMOND_BARDING, (short)0, new String[] {}));
        items.add(new EItem("Gold Horse Armor", Material.GOLD_BARDING, (short)0, new String[] {}));
        items.add(new EItem("Iron Horse Armor", Material.IRON_BARDING, (short)0, new String[] {}));
        items.add(new EItem("Leash", Material.LEASH, (short)0, new String[] {}));
        items.add(new EItem("Hay Bale", Material.HAY_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Name Tag", Material.NAME_TAG, (short)0, new String[] {}));
        items.add(new EItem("Hardened Clay", Material.HARD_CLAY, (short)0, new String[] {}));
        items.add(new EItem("Block of Coal", Material.COAL_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("White Stained Clay", Material.STAINED_CLAY, (short)0, new String[] {}));
        items.add(new EItem("Orange Stained Clay", Material.STAINED_CLAY, (short)1, new String[] {}));
        items.add(new EItem("Magenta Stained Clay", Material.STAINED_CLAY, (short)2, new String[] {}));
        items.add(new EItem("Light Blue Stained Clay", Material.STAINED_CLAY, (short)3, new String[] {}));
        items.add(new EItem("Yellow Stained Clay", Material.STAINED_CLAY, (short)4, new String[] {}));
        items.add(new EItem("Lime Stained Clay", Material.STAINED_CLAY, (short)5, new String[] {}));
        items.add(new EItem("Pink Stained Clay", Material.STAINED_CLAY, (short)6, new String[] {}));
        items.add(new EItem("Gray Stained Clay", Material.STAINED_CLAY, (short)7, new String[] {}));
        items.add(new EItem("Light Gray Stained Clay", Material.STAINED_CLAY, (short)8, new String[] {}));
        items.add(new EItem("Cyan Stained Clay", Material.STAINED_CLAY, (short)9, new String[] {}));
        items.add(new EItem("Purple Stained Clay", Material.STAINED_CLAY, (short)10, new String[] {}));
        items.add(new EItem("Blue Stained Clay", Material.STAINED_CLAY, (short)11, new String[] {}));
        items.add(new EItem("Brown Stained Clay", Material.STAINED_CLAY, (short)12, new String[] {}));
        items.add(new EItem("Green Stained Clay", Material.STAINED_CLAY, (short)13, new String[] {}));
        items.add(new EItem("Red Stained Clay", Material.STAINED_CLAY, (short)14, new String[] {}));
        items.add(new EItem("Black Stained Clay", Material.STAINED_CLAY, (short)15, new String[] {}));
        items.add(new EItem("White Carpet", Material.CARPET, (short)0, new String[] {}));
        items.add(new EItem("Orange Carpet", Material.CARPET, (short)1, new String[] {}));
        items.add(new EItem("Magenta Carpet", Material.CARPET, (short)2, new String[] {}));
        items.add(new EItem("Light Blue Carpet", Material.CARPET, (short)3, new String[] {}));
        items.add(new EItem("Yellow Carpet", Material.CARPET, (short)4, new String[] {}));
        items.add(new EItem("Light Green Carpet", Material.CARPET, (short)5, new String[] {}));
        items.add(new EItem("Pink Carpet", Material.CARPET, (short)6, new String[] {}));
        items.add(new EItem("Gray Carpet", Material.CARPET, (short)7, new String[] {}));
        items.add(new EItem("Light Gray Carpet", Material.CARPET, (short)8, new String[] {}));
        items.add(new EItem("Cyan Carpet", Material.CARPET, (short)9, new String[] {}));
        items.add(new EItem("Purple Carpet", Material.CARPET, (short)10, new String[] {}));
        items.add(new EItem("Blue Carpet", Material.CARPET, (short)11, new String[] {}));
        items.add(new EItem("Brown Carpet", Material.CARPET, (short)12, new String[] {}));
        items.add(new EItem("Dark Green Carpet", Material.CARPET, (short)13, new String[] {}));
        items.add(new EItem("Red Carpet", Material.CARPET, (short)14, new String[] {}));
        items.add(new EItem("Black Carpet", Material.CARPET, (short)15, new String[] {}));
        items.add(new EItem("Packed Ice", Material.PACKED_ICE, (short)0, new String[] {}));
        items.add(new EItem("Coarse Dirt", Material.DIRT, (short)1, new String[] {}));
        items.add(new EItem("Acacia Log", Material.LOG_2, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Log", Material.LOG_2, (short)1, new String[] {}));
        items.add(new EItem("Acacia Plank", Material.WOOD, (short)4, new String[] {"aplank"}));
        items.add(new EItem("Dark Oak Plank", Material.WOOD, (short)5, new String[] {"doplank"}));
        items.add(new EItem("Acacia Wood Stairs", Material.ACACIA_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Wood Stairs", Material.DARK_OAK_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Acacia Sapling", Material.SAPLING, (short)4, new String[] {}));
        items.add(new EItem("Dark Oak Sapling", Material.SAPLING, (short)5, new String[] {}));
        items.add(new EItem("Acacia Leaves", Material.LEAVES_2, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Leaves", Material.LEAVES_2, (short)1, new String[] {}));
        items.add(new EItem("Packed Ice", Material.PACKED_ICE, (short)0, new String[] {}));
        items.add(new EItem("Podzol", Material.DIRT, (short)2, new String[] {}));
        items.add(new EItem("Red Sand", Material.SAND, (short)1, new String[] {}));
        items.add(new EItem("Cobblestone Monster Egg", Material.MONSTER_EGGS, (short)1, new String[] {}));
        items.add(new EItem("Cracked Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)4, new String[] {}));
        items.add(new EItem("Chiseled Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)5, new String[] {}));
        items.add(new EItem("White Stained Glass", Material.STAINED_GLASS, (short)0, new String[] {}));
        items.add(new EItem("Orange Stained Glass", Material.STAINED_GLASS, (short)1, new String[] {}));
        items.add(new EItem("Magenta Stained Glass", Material.STAINED_GLASS, (short)2, new String[] {}));
        items.add(new EItem("Light Blue Stained Glass", Material.STAINED_GLASS, (short)3, new String[] {}));
        items.add(new EItem("Yellow Stained Glass", Material.STAINED_GLASS, (short)4, new String[] {}));
        items.add(new EItem("Light Green Stained Glass", Material.STAINED_GLASS, (short)5, new String[] {}));
        items.add(new EItem("Pink Stained Glass", Material.STAINED_GLASS, (short)6, new String[] {}));
        items.add(new EItem("Gray Stained Glass", Material.STAINED_GLASS, (short)7, new String[] {}));
        items.add(new EItem("Light Gray Stained Glass", Material.STAINED_GLASS, (short)8, new String[] {}));
        items.add(new EItem("Cyan Stained Glass", Material.STAINED_GLASS, (short)9, new String[] {}));
        items.add(new EItem("Purple Stained Glass", Material.STAINED_GLASS, (short)10, new String[] {}));
        items.add(new EItem("Blue Stained Glass", Material.STAINED_GLASS, (short)11, new String[] {}));
        items.add(new EItem("Brown Stained Glass", Material.STAINED_GLASS, (short)12, new String[] {}));
        items.add(new EItem("Dark Green Stained Glass", Material.STAINED_GLASS, (short)13, new String[] {}));
        items.add(new EItem("Red Stained Glass", Material.STAINED_GLASS, (short)14, new String[] {}));
        items.add(new EItem("Black Stained Glass", Material.STAINED_GLASS, (short)15, new String[] {}));
        items.add(new EItem("White Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)0, new String[] {}));
        items.add(new EItem("Orange Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)1, new String[] {}));
        items.add(new EItem("Magenta Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)2, new String[] {}));
        items.add(new EItem("Light Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)3, new String[] {}));
        items.add(new EItem("Yellow Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)4, new String[] {}));
        items.add(new EItem("Light Green Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)5, new String[] {}));
        items.add(new EItem("Pink Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)6, new String[] {}));
        items.add(new EItem("Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)7, new String[] {}));
        items.add(new EItem("Light Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)8, new String[] {}));
        items.add(new EItem("Cyan Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)9, new String[] {}));
        items.add(new EItem("Purple Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)10, new String[] {}));
        items.add(new EItem("Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)11, new String[] {}));
        items.add(new EItem("Brown Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)12, new String[] {}));
        items.add(new EItem("Dark Green Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)13, new String[] {}));
        items.add(new EItem("Red Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)14, new String[] {}));
        items.add(new EItem("Black Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)15, new String[] {}));
        items.add(new EItem("Poppy", Material.RED_ROSE, (short)0, new String[] {}));
        items.add(new EItem("Blue Orchid", Material.RED_ROSE, (short)1, new String[] {}));
        items.add(new EItem("Allium", Material.RED_ROSE, (short)2, new String[] {}));
        items.add(new EItem("Azure Bluet", Material.RED_ROSE, (short)3, new String[] {}));
        items.add(new EItem("Red Tulip", Material.RED_ROSE, (short)4, new String[] {}));
        items.add(new EItem("Orange Tulip", Material.RED_ROSE, (short)5, new String[] {}));
        items.add(new EItem("White Tulip", Material.RED_ROSE, (short)6, new String[] {}));
        items.add(new EItem("Pink Tulip", Material.RED_ROSE, (short)7, new String[] {}));
        items.add(new EItem("Oxeye Daisy", Material.RED_ROSE, (short)8, new String[] {}));
        items.add(new EItem("Sunflower", Material.DOUBLE_PLANT, (short)0, new String[] {}));
        items.add(new EItem("Lilac", Material.DOUBLE_PLANT, (short)1, new String[] {}));
        items.add(new EItem("Double Tallgrass", Material.DOUBLE_PLANT, (short)2, new String[] {}));
        items.add(new EItem("Large Fern", Material.DOUBLE_PLANT, (short)3, new String[] {}));
        items.add(new EItem("Rose Bush", Material.DOUBLE_PLANT, (short)4, new String[] {}));
        items.add(new EItem("Peony", Material.DOUBLE_PLANT, (short)5, new String[] {}));
        items.add(new EItem("Command Minecart", Material.COMMAND_MINECART, (short)0, new String[] {}));
        items.add(new EItem("Potion of Water Breathing", Material.POTION, (short)8205, new String[] {}));
        items.add(new EItem("Potion of Water Breathing (Reverted);", Material.POTION, (short)8237, new String[] {}));
        items.add(new EItem("Potion of Water Breathing (Extended);", Material.POTION, (short)8269, new String[] {}));
        items.add(new EItem("Splash Potion of Water Breathing", Material.POTION, (short)16397, new String[] {}));
        items.add(new EItem("Splash Potion of Water Breathing (Reverted);", Material.POTION, (short)16429, new String[] {}));
        items.add(new EItem("Splash Potion of Water Breathing (Extended);", Material.POTION, (short)16461, new String[] {}));
        items.add(new EItem("Raw Salmon", Material.RAW_FISH, (short)1, new String[] {}));
        items.add(new EItem("Cooked Salmon", Material.COOKED_FISH, (short)1, new String[] {}));
        items.add(new EItem("Clownfish", Material.RAW_FISH, (short)2, new String[] {}));
        items.add(new EItem("Pufferfish", Material.RAW_FISH, (short)3, new String[] {}));
        items.add(new EItem("Acacia Slab", Material.WOOD_STEP, (short)4, new String[] {}));
        items.add(new EItem("Dark Oak Slab", Material.WOOD_STEP, (short)5, new String[] {}));
        items.add(new EItem("Granite", Material.STONE, (short)1, new String[] {}));
        items.add(new EItem("Polished Granite", Material.STONE, (short)2, new String[] {}));
        items.add(new EItem("Diorite", Material.STONE, (short)3, new String[] {}));
        items.add(new EItem("Polished Diorite", Material.STONE, (short)4, new String[] {}));
        items.add(new EItem("Andesite", Material.STONE, (short)5, new String[] {}));
        items.add(new EItem("Polished Andesite", Material.STONE, (short)6, new String[] {}));
        items.add(new EItem("Slime Block", Material.SLIME_BLOCK, (short)0, new String[] {}));
        items.add(new EItem("Wet Sponge", Material.SPONGE, (short)1, new String[] {}));
        items.add(new EItem("Barrier", Material.BARRIER, (short)0, new String[] {}));
        items.add(new EItem("Iron Trapdoor", Material.IRON_TRAPDOOR, (short)0, new String[] {}));
        items.add(new EItem("Prismarine", Material.PRISMARINE, (short)0, new String[] {}));
        items.add(new EItem("Prismarine Bricks", Material.PRISMARINE, (short)1, new String[] {}));
        items.add(new EItem("Dark Prismarine", Material.PRISMARINE, (short)2, new String[] {}));
        items.add(new EItem("Sea Lantern", Material.SEA_LANTERN, (short)0, new String[] {}));
        items.add(new EItem("Red Sandstone", Material.RED_SANDSTONE, (short)0, new String[] {}));
        items.add(new EItem("Chiseled Red Sandstone", Material.RED_SANDSTONE, (short)1, new String[] {}));
        items.add(new EItem("Smooth Red Sandstone", Material.RED_SANDSTONE, (short)2, new String[] {}));
        items.add(new EItem("Red Sandstone Stairs", Material.RED_SANDSTONE_STAIRS, (short)0, new String[] {}));
        items.add(new EItem("Red Sandstone Slab", Material.STONE_SLAB2, (short)0, new String[] {}));
        items.add(new EItem("Spruce Fence Gate", Material.SPRUCE_FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Birch Fence Gate", Material.BIRCH_FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Jungle Fence Gate", Material.JUNGLE_FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Fence Gate", Material.DARK_OAK_FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Acacia Fence Gate", Material.ACACIA_FENCE_GATE, (short)0, new String[] {}));
        items.add(new EItem("Spruce Fence", Material.SPRUCE_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Birch Fence", Material.BIRCH_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Jungle Fence", Material.JUNGLE_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Fence", Material.DARK_OAK_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Acacia Fence", Material.ACACIA_FENCE, (short)0, new String[] {}));
        items.add(new EItem("Spruce Door", Material.SPRUCE_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Birch Door", Material.BIRCH_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Jungle Door", Material.JUNGLE_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Dark Oak Door", Material.DARK_OAK_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Acacia Door", Material.ACACIA_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new EItem("Prismarine Shard", Material.PRISMARINE_SHARD, (short)0, new String[] {}));
        items.add(new EItem("Prismarine Crystal", Material.PRISMARINE_CRYSTALS, (short)0, new String[] {}));
        items.add(new EItem("Raw Rabbit", Material.RABBIT, (short)0, new String[] {}));
        items.add(new EItem("Cooked Rabbit", Material.COOKED_RABBIT, (short)0, new String[] {}));
        items.add(new EItem("Rabbit Stew", Material.RABBIT_STEW, (short)0, new String[] {}));
        items.add(new EItem("Rabbit Foot", Material.RABBIT_FOOT, (short)0, new String[] {}));
        items.add(new EItem("Rabbit Hide", Material.RABBIT_HIDE, (short)0, new String[] {}));
        items.add(new EItem("Armor Stand", Material.ARMOR_STAND, (short)0, new String[] {}));
        items.add(new EItem("Raw Mutton", Material.MUTTON, (short)0, new String[] {}));
        items.add(new EItem("Cooked Mutton", Material.COOKED_MUTTON, (short)0, new String[] {}));
        items.add(new EItem("White Banner", Material.BANNER, (short)15, new String[] {}));
        items.add(new EItem("Orange Banner", Material.BANNER, (short)14, new String[] {}));
        items.add(new EItem("Magenta Banner", Material.BANNER, (short)13, new String[] {}));
        items.add(new EItem("Light Blue Banner", Material.BANNER, (short)12, new String[] {}));
        items.add(new EItem("Yellow Banner", Material.BANNER, (short)11, new String[] {}));
        items.add(new EItem("Lime Banner", Material.BANNER, (short)10, new String[] {}));
        items.add(new EItem("Pink Banner", Material.BANNER, (short)9, new String[] {}));
        items.add(new EItem("Gray Banner", Material.BANNER, (short)8, new String[] {}));
        items.add(new EItem("Light Gray Banner", Material.BANNER, (short)7, new String[] {}));
        items.add(new EItem("Cyan Banner", Material.BANNER, (short)6, new String[] {}));
        items.add(new EItem("Purple Banner", Material.BANNER, (short)5, new String[] {}));
        items.add(new EItem("Blue Banner", Material.BANNER, (short)4, new String[] {}));
        items.add(new EItem("Brown Banner", Material.BANNER, (short)3, new String[] {}));
        items.add(new EItem("Green Banner", Material.BANNER, (short)2, new String[] {}));
        items.add(new EItem("Red Banner", Material.BANNER, (short)1, new String[] {}));
        items.add(new EItem("Black Banner", Material.BANNER, (short)0, new String[] {}));
        items.add(new EItem("Potion of Leaping", Material.POTION, (short)8203, new String[] {}));
        items.add(new EItem("Potion of Leaping (Extended);", Material.POTION, (short)8267, new String[] {}));
        items.add(new EItem("Potion of Leaping II", Material.POTION, (short)8235, new String[] {}));
        items.add(new EItem("Splash Potion of Leaping", Material.POTION, (short)16395, new String[] {}));
        items.add(new EItem("Splash Potion of Leaping (Extended);", Material.POTION, (short)16459, new String[] {}));
        items.add(new EItem("Splash Potion of Leaping II", Material.POTION, (short)16427, new String[] {}));
        items.add(new EItem("Bat Spawn Egg", Material.MONSTER_EGG, (short)65, new String[] {}));
        items.add(new EItem("Witch Spawn Egg", Material.MONSTER_EGG, (short)66, new String[] {}));
        items.add(new EItem("Endermite Spawn Egg", Material.MONSTER_EGG, (short)67, new String[] {}));
        items.add(new EItem("Guardian Spawn Egg", Material.MONSTER_EGG, (short)68, new String[] {}));
        items.add(new EItem("Rabbit Spawn Egg", Material.MONSTER_EGG, (short)101, new String[] {}));

        for (EItem item : items) {
            itemLookup.put(item.getKey(), item);
        }
    }

}
