package com.clashwars.essence.aliases;

import org.bukkit.Material;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Items {

    private static final List<ItemAlias> items = new ArrayList<ItemAlias>();
    private static final HashMap<String, ItemAlias> itemLookup = new HashMap<String, ItemAlias>();

    public static List<ItemAlias> getItems() {
        return items;
    }

    public static ItemAlias getItem(Material material, short data) {
        String key = material.toString().toLowerCase() + "-" + data;
        if (itemLookup.containsKey(key)) {
            return itemLookup.get(key);
        }
        return null;
    }

    public static ItemAlias getItem(String string) {
        string = string.toLowerCase().trim();
        String[] split = string.split(":");
        string = split[0];
        short data = 0;
        if (split.length > 1) {
            try {
                data = Short.parseShort(split[1]);
            } catch (Exception e) {
            }
        }

        ItemAlias match = null;
        for (ItemAlias item : items) {
            if (item.getAliases().contains(string)) {
                match = item;
                break;
            }
        }

        if (match == null) {
            return null;
        }

        ItemAlias dataMatch = getItem(match.getType(), data);
        if (dataMatch == null) {
            return getItem(match.getType(), (short)0);
        }
        return dataMatch;
    }


    static {
        items.add(new ItemAlias("Air", Material.AIR, (short)0, new String[] {}));
        items.add(new ItemAlias("Stone", Material.STONE, (short)0, new String[] {"smoothstone", "rock"}));
        items.add(new ItemAlias("Grass", Material.GRASS, (short)0, new String[] {}));
        items.add(new ItemAlias("Dirt", Material.DIRT, (short)0, new String[] {"earth"}));
        items.add(new ItemAlias("Cobblestone", Material.COBBLESTONE, (short)0, new String[] {"cobble", "cstone"}));
        items.add(new ItemAlias("Oak Plank", Material.WOOD, (short)0, new String[] {"oplank", "woodenplank", "woodplank", "plankwooden", "plankwood", "plankw", "wplank", "oakp"}));
        items.add(new ItemAlias("Spruce Plank", Material.WOOD, (short)1, new String[] {"splank", "sprucep"}));
        items.add(new ItemAlias("Birch Plank", Material.WOOD, (short)2, new String[] {"bplank", "birchp"}));
        items.add(new ItemAlias("Jungle Plank", Material.WOOD, (short)3, new String[] {"jplank", "junglep"}));
        items.add(new ItemAlias("Oak Sapling", Material.SAPLING, (short)0, new String[] {"osapling", "treesapling", "logsapling", "smalltree"}));
        items.add(new ItemAlias("Spruce Sapling", Material.SAPLING, (short)1, new String[] {"ssapling"}));
        items.add(new ItemAlias("Birch Sapling", Material.SAPLING, (short)2, new String[] {"bsapling"}));
        items.add(new ItemAlias("Jungle Sapling", Material.SAPLING, (short)3, new String[] {"jsapling"}));
        items.add(new ItemAlias("Bedrock", Material.BEDROCK, (short)0, new String[] {"adminblock", "oprock", "adminrock", "adminium"}));
        items.add(new ItemAlias("Water", Material.WATER, (short)0, new String[] {"movingwater", "mwater", "flowingwater", "fwater"}));
        items.add(new ItemAlias("Lava", Material.LAVA, (short)0, new String[] {"movinglava", "mlava", "flowinglava", "flava"}));
        items.add(new ItemAlias("Sand", Material.SAND, (short)0, new String[] {}));
        items.add(new ItemAlias("Gold Ore", Material.GOLD_ORE, (short)0, new String[] {"oregold", "gore", "oreg", "goldo"}));
        items.add(new ItemAlias("Iron Ore", Material.IRON_ORE, (short)0, new String[] {"oreiron", "iore", "orei", "irono"}));
        items.add(new ItemAlias("Coal Ore", Material.COAL_ORE, (short)0, new String[] {"orecoal", "core", "orec", "coalo"}));
        items.add(new ItemAlias("Gravel", Material.GRAVEL, (short)0, new String[] {}));
        items.add(new ItemAlias("Oak Log", Material.LOG, (short)0, new String[] {"log", "trunk", "oak", "wood", "oakwood", "olog", "owood"}));
        items.add(new ItemAlias("Spruce Log", Material.LOG, (short)1, new String[] {"sprucewood", "slog", "swood"}));
        items.add(new ItemAlias("Birch Log", Material.LOG, (short)2, new String[] {"birchwood", "blog", "bwood"}));
        items.add(new ItemAlias("Jungle Log", Material.LOG, (short)3, new String[] {"junglewood", "jlog", "jwood"}));
        items.add(new ItemAlias("Leaves Block", Material.LEAVES, (short)0, new String[] {"decayleaf", "decayableleaf", "decayleaves", "decayableleaves", "dleaf", "dleaves"}));
        items.add(new ItemAlias("Spruce Leaves Block", Material.LEAVES, (short)1, new String[] {}));
        items.add(new ItemAlias("Birch Leaves Block", Material.LEAVES, (short)2, new String[] {}));
        items.add(new ItemAlias("Jungle Leaves Block", Material.LEAVES, (short)3, new String[] {}));
        items.add(new ItemAlias("Leaves", Material.LEAVES, (short)4, new String[] {"leaves", "leaf", "oakleaves", "oakleaf", "oleaves", "oleaf"}));
        items.add(new ItemAlias("Spruce Leaves", Material.LEAVES, (short)5, new String[] {"spruceleaves", "spruceleaf", "sleaves", "sleaf"}));
        items.add(new ItemAlias("Birch Leaves", Material.LEAVES, (short)6, new String[] {"birchleaves", "birchleaf", "bleaves", "bleaf"}));
        items.add(new ItemAlias("Jungle Leaves", Material.LEAVES, (short)7, new String[] {"jungleleaves", "jungleleaf", "jleaves", "jleaf"}));
        items.add(new ItemAlias("Sponge", Material.SPONGE, (short)0, new String[] {}));
        items.add(new ItemAlias("Glass", Material.GLASS, (short)0, new String[] {"glassblock", "blockglass"}));
        items.add(new ItemAlias("Lapis Lazuli Ore", Material.LAPIS_ORE, (short)0, new String[] {"lapisore", "lapiso", "lore", "orelapis", "orel", "orelapislazuli"}));
        items.add(new ItemAlias("Lapis Lazuli Block", Material.LAPIS_BLOCK, (short)0, new String[] {"lapisblock", "lblock", "llblock", "blocklapis"}));
        items.add(new ItemAlias("Dispenser", Material.DISPENSER, (short)0, new String[] {"dispense"}));
        items.add(new ItemAlias("Sandstone", Material.SANDSTONE, (short)0, new String[] {"sastone"}));
        items.add(new ItemAlias("Chiseled Sandstone", Material.SANDSTONE, (short)1, new String[] {"chiselsandstone", "chiseledss", "chiselss", "csstone", "creepersandstone", "creepsandstone", "creepersstone"}));
        items.add(new ItemAlias("Smooth Sandstone", Material.SANDSTONE, (short)2, new String[] {"smoothsand", "ssstone", "smoothss"}));
        items.add(new ItemAlias("Note Block", Material.NOTE_BLOCK, (short)0, new String[] {"nblock", "noteb", "note"}));
        items.add(new ItemAlias("Bed Block", Material.BED_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Powered Rail", Material.POWERED_RAIL, (short)0, new String[] {"prail", "prails", "ptrack", "poweredtrack", "boostrail", "boostrails", "boosttrack", "brail", "btrack", "brails"}));
        items.add(new ItemAlias("Detector Rail", Material.DETECTOR_RAIL, (short)0, new String[] {"drail", "drails", "dtrack", "detectortrack"}));
        items.add(new ItemAlias("Sticky Piston", Material.PISTON_STICKY_BASE, (short)0, new String[] {"stickyp", "spiston", "psticky", "pistonsticky"}));
        items.add(new ItemAlias("Web", Material.WEB, (short)0, new String[] {"cobweb", "spiderweb", "cweb", "sweb"}));
        items.add(new ItemAlias("Dead Shrub", Material.LONG_GRASS, (short)0, new String[] {"dshrub", "shrub"}));
        items.add(new ItemAlias("Tall Grass", Material.LONG_GRASS, (short)1, new String[] {"tgrass", "longgrass", "lgrass", "grasstall", "grasst", "grasslong", "grassl"}));
        items.add(new ItemAlias("Fern", Material.LONG_GRASS, (short)2, new String[] {}));
        items.add(new ItemAlias("Piston", Material.PISTON_BASE, (short)0, new String[] {}));
        items.add(new ItemAlias("White Wool", Material.WOOL, (short)0, new String[] {"wool", "cloth", "whitecloth", "whitew"}));
        items.add(new ItemAlias("Orange Wool", Material.WOOL, (short)1, new String[] {"orangecloth", "orangew"}));
        items.add(new ItemAlias("Magenta Wool", Material.WOOL, (short)2, new String[] {"magentacloth", "magentaw"}));
        items.add(new ItemAlias("Light Blue Wool", Material.WOOL, (short)3, new String[] {"lightbluecloth", "lightbluew"}));
        items.add(new ItemAlias("Yellow Wool", Material.WOOL, (short)4, new String[] {"yellowcloth", "yelloww"}));
        items.add(new ItemAlias("Light Green Wool", Material.WOOL, (short)5, new String[] {"greencloth", "greenw", "greenwool"}));
        items.add(new ItemAlias("Pink Wool", Material.WOOL, (short)6, new String[] {"pinkcloth", "pinkw"}));
        items.add(new ItemAlias("Gray Wool", Material.WOOL, (short)7, new String[] {"graycloth", "grayw", "darkgraywool"}));
        items.add(new ItemAlias("Light Gray Wool", Material.WOOL, (short)8, new String[] {"lightgraycloth", "lightgrayw"}));
        items.add(new ItemAlias("Cyan Wool", Material.WOOL, (short)9, new String[] {"cyancloth", "cyanw"}));
        items.add(new ItemAlias("Purple Wool", Material.WOOL, (short)10, new String[] {"purplecloth", "purplew"}));
        items.add(new ItemAlias("Blue Wool", Material.WOOL, (short)11, new String[] {"bluecloth", "bluew"}));
        items.add(new ItemAlias("Brown Wool", Material.WOOL, (short)12, new String[] {"browncloth", "brownw"}));
        items.add(new ItemAlias("Dark Green Wool", Material.WOOL, (short)13, new String[] {"darkgreencloth", "darkgreenw"}));
        items.add(new ItemAlias("Red Wool", Material.WOOL, (short)14, new String[] {"redcloth", "redw"}));
        items.add(new ItemAlias("Black Wool", Material.WOOL, (short)15, new String[] {"blackcloth", "blackw"}));
        items.add(new ItemAlias("Dandelion", Material.YELLOW_FLOWER, (short)0, new String[] {"yellowflower"}));
        items.add(new ItemAlias("Brown Mushroom", Material.BROWN_MUSHROOM, (short)0, new String[] {"brownshroom"}));
        items.add(new ItemAlias("Red Mushroom", Material.RED_MUSHROOM, (short)0, new String[] {"redshroom"}));
        items.add(new ItemAlias("Gold Block", Material.GOLD_BLOCK, (short)0, new String[] {"gblock", "blockgold", "goldb"}));
        items.add(new ItemAlias("Iron Block", Material.IRON_BLOCK, (short)0, new String[] {"iblock", "blockiron", "ironb"}));
        items.add(new ItemAlias("Double Stone Slab", Material.DOUBLE_STEP, (short)0, new String[] {}));
        items.add(new ItemAlias("Double Sandstone Slab", Material.DOUBLE_STEP, (short)1, new String[] {}));
        items.add(new ItemAlias("Double Wooden Slab", Material.DOUBLE_STEP, (short)2, new String[] {"doublewoodslab", "wooddoubleslab", "woodendoubleslab", "wooddslab", "woodendslab", "doubleslabwood", "doubleslabwooden", "dslabwood", "dslabwooden"}));
        items.add(new ItemAlias("Double Cobblestone Slab", Material.DOUBLE_STEP, (short)3, new String[] {"doublecobbleslab", "cobbledoubleslab", "cobbleslab", "doubleslabcobble", "dslabcobble"}));
        items.add(new ItemAlias("Double Brick Slab", Material.DOUBLE_STEP, (short)4, new String[] {"brickdoubleslab", "slabbrickdouble", "brickslabdouble", "dbrickslab", "brickdslab"}));
        items.add(new ItemAlias("Double Stone Brick Slab", Material.DOUBLE_STEP, (short)5, new String[] {"stonebrickdoubleslab", "stonebrickdslab"}));
        items.add(new ItemAlias("Double Smooth Sandstone Slab", Material.DOUBLE_STEP, (short)9, new String[] {"smoothsandstonedoubleslab", "smoothsandstonedslab", "dsmoothsandstoneslab"}));
        items.add(new ItemAlias("Stone Slab", Material.STEP, (short)0, new String[] {"stonestep"}));
        items.add(new ItemAlias("Sandstone Slab", Material.STEP, (short)1, new String[] {"sandstonestep"}));
        items.add(new ItemAlias("Wooden Slab", Material.STEP, (short)2, new String[] {"woodenstep", "woodslab", "woodstep"}));
        items.add(new ItemAlias("Cobblestone Slab", Material.STEP, (short)3, new String[] {"cobbleslab", "cobblestonestep", "cobblestep"}));
        items.add(new ItemAlias("Brick Slab", Material.STEP, (short)4, new String[] {"brickstep"}));
        items.add(new ItemAlias("Stone Brick Slab", Material.STEP, (short)5, new String[] {"stonebrickstep"}));
        items.add(new ItemAlias("Brick", Material.BRICK, (short)0, new String[] {"brickblock"}));
        items.add(new ItemAlias("TNT", Material.TNT, (short)0, new String[] {}));
        items.add(new ItemAlias("Bookshelf", Material.BOOKSHELF, (short)0, new String[] {}));
        items.add(new ItemAlias("Moss Stone", Material.MOSSY_COBBLESTONE, (short)0, new String[] {}));
        items.add(new ItemAlias("Obsidian", Material.OBSIDIAN, (short)0, new String[] {}));
        items.add(new ItemAlias("Torch", Material.TORCH, (short)0, new String[] {}));
        items.add(new ItemAlias("Fire", Material.FIRE, (short)0, new String[] {}));
        items.add(new ItemAlias("Monster Spawner", Material.MOB_SPAWNER, (short)0, new String[] {"spawner"}));
        items.add(new ItemAlias("Oak Wood Stairs", Material.WOOD_STAIRS, (short)0, new String[] {"oakstairs", "woodstairs", "woodenstairs"}));
        items.add(new ItemAlias("Jungle Wood Stairs", Material.JUNGLE_WOOD_STAIRS, (short)0, new String[] {"junglestairs"}));
        items.add(new ItemAlias("Spruce Wood Stairs", Material.SPRUCE_WOOD_STAIRS, (short)0, new String[] {"sprucestairs"}));
        items.add(new ItemAlias("Birch Wood Stairs", Material.BIRCH_WOOD_STAIRS, (short)0, new String[] {"birchstairs"}));
        items.add(new ItemAlias("Chest", Material.CHEST, (short)0, new String[] {}));
        items.add(new ItemAlias("Diamond Ore", Material.DIAMOND_ORE, (short)0, new String[] {"diaore"}));
        items.add(new ItemAlias("Diamond Block", Material.DIAMOND_BLOCK, (short)0, new String[] {"diablock"}));
        items.add(new ItemAlias("Crafting Table", Material.WORKBENCH, (short)0, new String[] {"worktable", "workbench"}));
        items.add(new ItemAlias("Farmland", Material.SOIL, (short)0, new String[] {"tilleddirt", "tilledearth"}));
        items.add(new ItemAlias("Furnace", Material.FURNACE, (short)0, new String[] {}));
        items.add(new ItemAlias("Ladder", Material.LADDER, (short)0, new String[] {}));
        items.add(new ItemAlias("Rails", Material.RAILS, (short)0, new String[] {"rail"}));
        items.add(new ItemAlias("Cobblestone Stairs", Material.COBBLESTONE_STAIRS, (short)0, new String[] {"cobblestairs"}));
        items.add(new ItemAlias("Lever", Material.LEVER, (short)0, new String[] {"switch"}));
        items.add(new ItemAlias("Stone Pressure Plate", Material.STONE_PLATE, (short)0, new String[] {"stoneplate"}));
        items.add(new ItemAlias("Wooden Pressure Plate", Material.WOOD_PLATE, (short)0, new String[] {"woodenplate", "woodplate"}));
        items.add(new ItemAlias("Redstone Ore", Material.REDSTONE_ORE, (short)0, new String[] {}));
        items.add(new ItemAlias("Redstone Torch", Material.REDSTONE_TORCH_ON, (short)0, new String[] {}));
        items.add(new ItemAlias("Stone Button", Material.STONE_BUTTON, (short)0, new String[] {}));
        items.add(new ItemAlias("Snow", Material.SNOW, (short)0, new String[] {}));
        items.add(new ItemAlias("Ice", Material.ICE, (short)0, new String[] {}));
        items.add(new ItemAlias("Snow Block", Material.SNOW_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Cactus", Material.CACTUS, (short)0, new String[] {"cacti", "cactuses"}));
        items.add(new ItemAlias("Clay Block", Material.CLAY, (short)0, new String[] {}));
        items.add(new ItemAlias("Jukebox", Material.JUKEBOX, (short)0, new String[] {"musicplayer"}));
        items.add(new ItemAlias("Oak Fence", Material.FENCE, (short)0, new String[] {"woodfence", "woodenfence", "fence"}));
        items.add(new ItemAlias("Pumpkin", Material.PUMPKIN, (short)0, new String[] {}));
        items.add(new ItemAlias("Netherrack", Material.NETHERRACK, (short)0, new String[] {}));
        items.add(new ItemAlias("Soul Sand", Material.SOUL_SAND, (short)0, new String[] {"nethersand"}));
        items.add(new ItemAlias("Glowstone", Material.GLOWSTONE, (short)0, new String[] {"glowstoneblock"}));
        items.add(new ItemAlias("Portal", Material.PORTAL, (short)0, new String[] {"portalblock"}));
        items.add(new ItemAlias("Jack-O-Lantern", Material.JACK_O_LANTERN, (short)0, new String[] {"jackolantern"}));
        items.add(new ItemAlias("Wooden Trapdoor", Material.TRAP_DOOR, (short)0, new String[] {"woodtrapdoor", "trapdoor"}));
        items.add(new ItemAlias("Stone Monster Egg", Material.MONSTER_EGGS, (short)0, new String[] {"stoneegg"}));
        items.add(new ItemAlias("Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)2, new String[] {"stonebrickegg"}));
        items.add(new ItemAlias("Mossy Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)3, new String[] {"mossystonebrickegg"}));
        items.add(new ItemAlias("Huge Brown Mushroom", Material.HUGE_MUSHROOM_1, (short)0, new String[] {"bigbrownmushroom", "hugebrownshroom", "bigbrownshroom"}));
        items.add(new ItemAlias("Huge Red Mushroom", Material.HUGE_MUSHROOM_2, (short)0, new String[] {"bigredmushroom", "hugeredshroom", "bigredshroom"}));
        items.add(new ItemAlias("Stone Brick", Material.SMOOTH_BRICK, (short)0, new String[] {"smoothbrick"}));
        items.add(new ItemAlias("Iron Fence", Material.IRON_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Glass Pane", Material.THIN_GLASS, (short)0, new String[] {"pane"}));
        items.add(new ItemAlias("Melon Block", Material.MELON_BLOCK, (short)0, new String[] {"grownmelon"}));
        items.add(new ItemAlias("Mossy Stone Brick", Material.SMOOTH_BRICK, (short)1, new String[] {}));
        items.add(new ItemAlias("Cracked Stone Brick", Material.SMOOTH_BRICK, (short)2, new String[] {}));
        items.add(new ItemAlias("Chiseled Stone Brick", Material.SMOOTH_BRICK, (short)3, new String[] {}));
        items.add(new ItemAlias("Brick Stairs", Material.BRICK_STAIRS, (short)0, new String[] {"brickstair"}));
        items.add(new ItemAlias("Fence Gate", Material.FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Vines", Material.VINE, (short)0, new String[] {"vine"}));
        items.add(new ItemAlias("Stone Brick Stairs", Material.SMOOTH_STAIRS, (short)0, new String[] {"stonebrickstair"}));
        items.add(new ItemAlias("Iron Shovel", Material.IRON_SPADE, (short)0, new String[] {"ishovel", "ironspade", "ispade"}));
        items.add(new ItemAlias("Iron Pickaxe", Material.IRON_PICKAXE, (short)0, new String[] {"ironpick", "ipick"}));
        items.add(new ItemAlias("Iron Axe", Material.IRON_AXE, (short)0, new String[] {"iaxe"}));
        items.add(new ItemAlias("Flint and Steel", Material.FLINT_AND_STEEL, (short)0, new String[] {"lighter"}));
        items.add(new ItemAlias("Apple", Material.APPLE, (short)0, new String[] {}));
        items.add(new ItemAlias("Bow", Material.BOW, (short)0, new String[] {"bowandarrow"}));
        items.add(new ItemAlias("Arrow", Material.ARROW, (short)0, new String[] {}));
        items.add(new ItemAlias("Coal", Material.COAL, (short)0, new String[] {}));
        items.add(new ItemAlias("Charcoal", Material.COAL, (short)1, new String[] {"treecoal", "logcoal"}));
        items.add(new ItemAlias("Diamond", Material.DIAMOND, (short)0, new String[] {"dia"}));
        items.add(new ItemAlias("Iron Ingot", Material.IRON_INGOT, (short)0, new String[] {"iron", "iingot"}));
        items.add(new ItemAlias("Gold Ingot", Material.GOLD_INGOT, (short)0, new String[] {"gold", "gingot"}));
        items.add(new ItemAlias("Iron Sword", Material.IRON_SWORD, (short)0, new String[] {"isword"}));
        items.add(new ItemAlias("Wooden Sword", Material.WOOD_SWORD, (short)0, new String[] {"wsword", "woodsword"}));
        items.add(new ItemAlias("Wooden Shovel", Material.WOOD_SPADE, (short)0, new String[] {"wshovel", "woodshovel"}));
        items.add(new ItemAlias("Wooden Pickaxe", Material.WOOD_PICKAXE, (short)0, new String[] {"woodpick", "woodpickaxe", "wpick", "wpickaxe"}));
        items.add(new ItemAlias("Wooden Axe", Material.WOOD_AXE, (short)0, new String[] {"woodaxe", "waxe"}));
        items.add(new ItemAlias("Stone Sword", Material.STONE_SWORD, (short)0, new String[] {"ssword"}));
        items.add(new ItemAlias("Stone Shovel", Material.STONE_SPADE, (short)0, new String[] {"stonespade", "sshovel", "sspade"}));
        items.add(new ItemAlias("Stone Pickaxe", Material.STONE_PICKAXE, (short)0, new String[] {"stonepick", "spick", "spickaxe"}));
        items.add(new ItemAlias("Stone Axe", Material.STONE_AXE, (short)0, new String[] {"saxe"}));
        items.add(new ItemAlias("Diamond Sword", Material.DIAMOND_SWORD, (short)0, new String[] {"diasword", "dsword"}));
        items.add(new ItemAlias("Diamond Shovel", Material.DIAMOND_SPADE, (short)0, new String[] {"diashovel", "dshovel"}));
        items.add(new ItemAlias("Diamond Pickaxe", Material.DIAMOND_PICKAXE, (short)0, new String[] {"diapick", "diapickaxe", "diamondpick", "dpick", "dpickaxe"}));
        items.add(new ItemAlias("Diamond Axe", Material.DIAMOND_AXE, (short)0, new String[] {"diaaxe", "daxe"}));
        items.add(new ItemAlias("Stick", Material.STICK, (short)0, new String[] {"sticks"}));
        items.add(new ItemAlias("Bowl", Material.BOWL, (short)0, new String[] {"mushroombowl", "shroombowl"}));
        items.add(new ItemAlias("Mushroom Soup", Material.MUSHROOM_SOUP, (short)0, new String[] {"soup", "shroomsoup"}));
        items.add(new ItemAlias("Gold Sword", Material.GOLD_SWORD, (short)0, new String[] {"gsword"}));
        items.add(new ItemAlias("Gold Shovel", Material.GOLD_SPADE, (short)0, new String[] {"gshovel", "gspade", "goldspade"}));
        items.add(new ItemAlias("Gold Pickaxe", Material.GOLD_PICKAXE, (short)0, new String[] {"gpickaxe", "gpick", "goldpick"}));
        items.add(new ItemAlias("Gold Axe", Material.GOLD_AXE, (short)0, new String[] {"gaxe"}));
        items.add(new ItemAlias("String", Material.STRING, (short)0, new String[] {}));
        items.add(new ItemAlias("Feather", Material.FEATHER, (short)0, new String[] {}));
        items.add(new ItemAlias("Gunpowder", Material.SULPHUR, (short)0, new String[] {"powder", "sulfur", "sulphur"}));
        items.add(new ItemAlias("Wooden Hoe", Material.WOOD_HOE, (short)0, new String[] {"whoe", "woodhoe"}));
        items.add(new ItemAlias("Stone Hoe", Material.STONE_HOE, (short)0, new String[] {"shoe"}));
        items.add(new ItemAlias("Iron Hoe", Material.IRON_HOE, (short)0, new String[] {"ihoe"}));
        items.add(new ItemAlias("Diamond Hoe", Material.DIAMOND_HOE, (short)0, new String[] {"diahoe", "dhoe"}));
        items.add(new ItemAlias("Gold Hoe", Material.GOLD_HOE, (short)0, new String[] {"ghoe"}));
        items.add(new ItemAlias("Seeds", Material.SEEDS, (short)0, new String[] {"seed"}));
        items.add(new ItemAlias("Wheat", Material.WHEAT, (short)0, new String[] {}));
        items.add(new ItemAlias("Bread", Material.BREAD, (short)0, new String[] {}));
        items.add(new ItemAlias("Leather Cap", Material.LEATHER_HELMET, (short)0, new String[] {"leatherhelmet", "leatherhelm",  "lhelmet", "lhelm", "lcap"}));
        items.add(new ItemAlias("Leather Tunic", Material.LEATHER_CHESTPLATE, (short)0, new String[] {"leatherchestplate", "leatherchest", "ltunic", "lchestplate", "lchest"}));
        items.add(new ItemAlias("Leather Pants", Material.LEATHER_LEGGINGS, (short)0, new String[] {"lleggings", "leatherpants", "lpants"}));
        items.add(new ItemAlias("Leather Boots", Material.LEATHER_BOOTS, (short)0, new String[] {"lboots", "lshoes", "leathershoes"}));
        items.add(new ItemAlias("Chainmail Helmet", Material.CHAINMAIL_HELMET, (short)0, new String[] {"chelmet", "chelm", "chainhelmet", "chainhelm", "chelmet"}));
        items.add(new ItemAlias("Chainmail Chestplate", Material.CHAINMAIL_CHESTPLATE, (short)0, new String[] {"cchest", "chainchest", "chainchestplate", "cchestplate"}));
        items.add(new ItemAlias("Chainmail Leggings", Material.CHAINMAIL_LEGGINGS, (short)0, new String[] {"cleggings", "cpants", "chainleggings", "chainpants", "chainmailpants"}));
        items.add(new ItemAlias("Chainmail Boots", Material.CHAINMAIL_BOOTS, (short)0, new String[] {"chainboots", "cboots", "cshoes", "chainshoes", "chainmailshoes"}));
        items.add(new ItemAlias("Iron Helmet", Material.IRON_HELMET, (short)0, new String[] {"ironhelm", "ihelm", "ihelmet"}));
        items.add(new ItemAlias("Iron Chestplate", Material.IRON_CHESTPLATE, (short)0, new String[] {"ichest", "ichestplate", "ironchest"}));
        items.add(new ItemAlias("Iron Leggings", Material.IRON_LEGGINGS, (short)0, new String[] {"ileggings", "ipants", "ironpants"}));
        items.add(new ItemAlias("Iron Boots", Material.IRON_BOOTS, (short)0, new String[] {"iboots", "ishoes"}));
        items.add(new ItemAlias("Diamond Helmet", Material.DIAMOND_HELMET, (short)0, new String[] {"diamondhelm", "diahelm", "diahelmet"}));
        items.add(new ItemAlias("Diamond Chestplate", Material.DIAMOND_CHESTPLATE, (short)0, new String[] {"diachest", "diachestplate", "diamondchest", "dchest", "dchestplate"}));
        items.add(new ItemAlias("Diamond Leggings", Material.DIAMOND_LEGGINGS, (short)0, new String[] {"diamondpants", "diapants", "dialeggings", "dleggings", "dpants"}));
        items.add(new ItemAlias("Diamond Boots", Material.DIAMOND_BOOTS, (short)0, new String[] {"diaboots", "dshoes", "diashoes", "dboots"}));
        items.add(new ItemAlias("Gold Helmet", Material.GOLD_HELMET, (short)0, new String[] {"ghelm", "goldhelm", "ghelmet"}));
        items.add(new ItemAlias("Gold Chestplate", Material.GOLD_CHESTPLATE, (short)0, new String[] {"gchest", "goldchest", "gchestplate"}));
        items.add(new ItemAlias("Gold Leggings", Material.GOLD_LEGGINGS, (short)0, new String[] {"gleggings", "glegs", "gpants", "goldlegs", "goldpants"}));
        items.add(new ItemAlias("Gold Boots", Material.GOLD_BOOTS, (short)0, new String[] {"gshoes", "goldshoes", "gboots"}));
        items.add(new ItemAlias("Flint", Material.FLINT, (short)0, new String[] {}));
        items.add(new ItemAlias("Raw Porkchop", Material.PORK, (short)0, new String[] {"rawpork", "pork", "porkchop"}));
        items.add(new ItemAlias("Cooked Porkchop", Material.GRILLED_PORK, (short)0, new String[] {"cpork", "cporkchop", "cookedpork"}));
        items.add(new ItemAlias("Paintings", Material.PAINTING, (short)0, new String[] {"painting", "paint"}));
        items.add(new ItemAlias("Golden Apple", Material.GOLDEN_APPLE, (short)0, new String[] {"gapple"}));
        items.add(new ItemAlias("Enchanted Golden Apple", Material.GOLDEN_APPLE, (short)1, new String[] {"godapple", "enchantgoldapple", "enchantgapple"}));
        items.add(new ItemAlias("Sign", Material.SIGN, (short)0, new String[] {}));
        items.add(new ItemAlias("Wooden Door", Material.WOOD_DOOR, (short)0, new String[] {"wooddoor", "wdoor", "door"}));
        items.add(new ItemAlias("Bucket", Material.BUCKET, (short)0, new String[] {}));
        items.add(new ItemAlias("Water Bucket", Material.WATER_BUCKET, (short)0, new String[] {"wbucket"}));
        items.add(new ItemAlias("Lava Bucket", Material.LAVA_BUCKET, (short)0, new String[] {"lbucket"}));
        items.add(new ItemAlias("Minecart", Material.MINECART, (short)0, new String[] {"cart"}));
        items.add(new ItemAlias("Saddle", Material.SADDLE, (short)0, new String[] {}));
        items.add(new ItemAlias("Iron Door", Material.IRON_DOOR, (short)0, new String[] {"steeldoor", "sdoor", "idoor"}));
        items.add(new ItemAlias("Redstone Dust", Material.REDSTONE, (short)0, new String[] {"reddust", "rsdust", "rdust", "redstone"}));
        items.add(new ItemAlias("Snowball", Material.SNOW_BALL, (short)0, new String[] {}));
        items.add(new ItemAlias("Boat", Material.BOAT, (short)0, new String[] {}));
        items.add(new ItemAlias("Leather", Material.LEATHER, (short)0, new String[] {}));
        items.add(new ItemAlias("Milk Bucket", Material.MILK_BUCKET, (short)0, new String[] {"mbucket"}));
        items.add(new ItemAlias("Clay Brick", Material.CLAY_BRICK, (short)0, new String[] {"cbrick"}));
        items.add(new ItemAlias("Clay", Material.CLAY_BALL, (short)0, new String[] {"clayball", "clayballs"}));
        items.add(new ItemAlias("Sugar Cane", Material.SUGAR_CANE, (short)0, new String[] {"reed", "reeds"}));
        items.add(new ItemAlias("Paper", Material.PAPER, (short)0, new String[] {}));
        items.add(new ItemAlias("Book", Material.BOOK, (short)0, new String[] {}));
        items.add(new ItemAlias("Slimeball", Material.SLIME_BALL, (short)0, new String[] {"slime", "sball"}));
        items.add(new ItemAlias("Storage Minecart", Material.STORAGE_MINECART, (short)0, new String[] {"storagemcart", "chestcart", "chestminecart"}));
        items.add(new ItemAlias("Powered Minecart", Material.POWERED_MINECART, (short)0, new String[] {"powercart", "powerminecart", "furnaceminecart", "furnacecart", "enginecart", "engineminecart"}));
        items.add(new ItemAlias("Egg", Material.EGG, (short)0, new String[] {}));
        items.add(new ItemAlias("Compass", Material.COMPASS, (short)0, new String[] {}));
        items.add(new ItemAlias("Fishing Rod", Material.FISHING_ROD, (short)0, new String[] {"fishrod", "frod", "rod"}));
        items.add(new ItemAlias("Clock", Material.WATCH, (short)0, new String[] {}));
        items.add(new ItemAlias("Glowstone Dust", Material.GLOWSTONE_DUST, (short)0, new String[] {"glowingstonedust", "gstonedust"}));
        items.add(new ItemAlias("Raw Fish", Material.RAW_FISH, (short)0, new String[] {"rfish", "fish"}));
        items.add(new ItemAlias("Cooked Fish", Material.COOKED_FISH, (short)0, new String[] {"cfish", "cookfish"}));
        items.add(new ItemAlias("Ink Sac", Material.INK_SACK, (short)0, new String[] {"inksack", "dye", "sack", "sac"}));
        items.add(new ItemAlias("Red Dye", Material.INK_SACK, (short)1, new String[] {"red"}));
        items.add(new ItemAlias("Cactus Green", Material.INK_SACK, (short)2, new String[] {"greendye", "cactusdye", "cactusgreendye"}));
        items.add(new ItemAlias("Cocoa Beans", Material.INK_SACK, (short)3, new String[] {"cocoa", "beans"}));
        items.add(new ItemAlias("Lapis Lazuli", Material.INK_SACK, (short)4, new String[] {"lapis", "lazuli", "bluedye", "blue"}));
        items.add(new ItemAlias("Purple Dye", Material.INK_SACK, (short)5, new String[] {"purple"}));
        items.add(new ItemAlias("Cyan Dye", Material.INK_SACK, (short)6, new String[] {"cyan"}));
        items.add(new ItemAlias("Light Gray Dye", Material.INK_SACK, (short)7, new String[] {"lightgreydye", "lightgray", "lightgrey", "lgraydye", "lgreydye"}));
        items.add(new ItemAlias("Gray Dye", Material.INK_SACK, (short)8, new String[] {"greydye", "gray", "grey"}));
        items.add(new ItemAlias("Pink Dye", Material.INK_SACK, (short)9, new String[] {"pink"}));
        items.add(new ItemAlias("Lime Dye", Material.INK_SACK, (short)10, new String[] {"lime"}));
        items.add(new ItemAlias("Dandelion Yellow", Material.INK_SACK, (short)11, new String[] {"yellow", "yellowdye", "yellowflowerdye"}));
        items.add(new ItemAlias("Light Blue Dye", Material.INK_SACK, (short)12, new String[] {"lbdye", "lightblue", "lb"}));
        items.add(new ItemAlias("Magenta Dye", Material.INK_SACK, (short)13, new String[] {"magenta", "mdye"}));
        items.add(new ItemAlias("Orange Dye", Material.INK_SACK, (short)14, new String[] {"orange", "odye"}));
        items.add(new ItemAlias("Bone Meal", Material.INK_SACK, (short)15, new String[] {"meal", "white", "whitedye", "wdye"}));
        items.add(new ItemAlias("Bone", Material.BONE, (short)0, new String[] {"bones"}));
        items.add(new ItemAlias("Sugar", Material.SUGAR, (short)0, new String[] {}));
        items.add(new ItemAlias("Cake", Material.CAKE, (short)0, new String[] {"lie"}));
        items.add(new ItemAlias("Melon Slice", Material.MELON, (short)0, new String[] {"melon", "mslice"}));
        items.add(new ItemAlias("Pumpkin Seed", Material.PUMPKIN_SEEDS, (short)0, new String[] {"pseed"}));
        items.add(new ItemAlias("Melon Seed", Material.MELON_SEEDS, (short)0, new String[] {"mseed"}));
        items.add(new ItemAlias("Raw Beef", Material.RAW_BEEF, (short)0, new String[] {"uncookedbeef", "uncookedsteak", "rbeef", "rawsteak", "rsteak"}));
        items.add(new ItemAlias("Steak", Material.COOKED_BEEF, (short)0, new String[] {"beef"}));
        items.add(new ItemAlias("Raw Chicken", Material.RAW_CHICKEN, (short)0, new String[] {"uncookedchicken", "rawchick", "rchick", "rchicken"}));
        items.add(new ItemAlias("Cooked Chicken", Material.COOKED_CHICKEN, (short)0, new String[] {"cchick", "cchicken", "cookedchick", "kfc"}));
        items.add(new ItemAlias("Rotten Flesh", Material.ROTTEN_FLESH, (short)0, new String[] {"rflesh", "flesh", "zombieflesh", "zflesh"}));
        items.add(new ItemAlias("Bed", Material.BED, (short)0, new String[] {}));
        items.add(new ItemAlias("Redstone Repeater", Material.DIODE, (short)0, new String[] {"repeater", "repeator"}));
        items.add(new ItemAlias("Cookie", Material.COOKIE, (short)0, new String[] {}));
        items.add(new ItemAlias("Map", Material.MAP, (short)0, new String[] {}));
        items.add(new ItemAlias("Empty Map", Material.EMPTY_MAP, (short)0, new String[] {"emap"}));
        items.add(new ItemAlias("Shears", Material.SHEARS, (short)0, new String[] {"sheers", "shear", "sheer", "woolcutters", "woolcutter"}));
        items.add(new ItemAlias("Ender Pearl", Material.ENDER_PEARL, (short)0, new String[] {"pearl", "epearl"}));
        items.add(new ItemAlias("Mycelium", Material.MYCEL, (short)0, new String[] {"mycel", "shroomgrass", "mushroomgrass"}));
        items.add(new ItemAlias("Lily Pad", Material.WATER_LILY, (short)0, new String[] {"lillypad", "lilly", "lily", "lpad", "pad"}));
        items.add(new ItemAlias("Cauldron Block", Material.CAULDRON, (short)0, new String[] {}));
        items.add(new ItemAlias("Cauldron", Material.CAULDRON_ITEM, (short)0, new String[] {"cauldron"}));
        items.add(new ItemAlias("Enchantment Table", Material.ENCHANTMENT_TABLE, (short)0, new String[] {"enchanttable", "magictable"}));
        items.add(new ItemAlias("Brewing Stand Block", Material.BREWING_STAND, (short)0, new String[] {}));
        items.add(new ItemAlias("Brewing Stand", Material.BREWING_STAND_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Brick", Material.NETHER_BRICK, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Brick Fence", Material.NETHER_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Netherwarts", Material.NETHER_WARTS, (short)0, new String[] {}));
        items.add(new ItemAlias("Netherstalk", Material.NETHER_STALK, (short)0, new String[] {}));
        items.add(new ItemAlias("End Portal", Material.ENDER_PORTAL, (short)0, new String[] {"enderportal"}));
        items.add(new ItemAlias("End Portal Frame", Material.ENDER_PORTAL_FRAME, (short)0, new String[] {"starframe"}));
        items.add(new ItemAlias("End Stone", Material.ENDER_STONE, (short)0, new String[] {"enderstone"}));
        items.add(new ItemAlias("Dragon Egg", Material.DRAGON_EGG, (short)0, new String[] {}));
        items.add(new ItemAlias("Blaze Rod", Material.BLAZE_ROD, (short)0, new String[] {"brod"}));
        items.add(new ItemAlias("Ghast Tear", Material.GHAST_TEAR, (short)0, new String[] {"tear"}));
        items.add(new ItemAlias("Gold Nugget", Material.GOLD_NUGGET, (short)0, new String[] {"nugget", "gnugget"}));
        items.add(new ItemAlias("Glass Bottle", Material.GLASS_BOTTLE, (short)0, new String[] {"emptypot", "emptybottle", "bottle", "potionbottle", "emptypotion"}));
        items.add(new ItemAlias("Potion", Material.POTION, (short)0, new String[] {}));
        items.add(new ItemAlias("Water Bottle", Material.POTION, (short)0, new String[] {"wbottle"}));
        items.add(new ItemAlias("Awkward Potion", Material.POTION, (short)16, new String[] {"awkpot", "awkpotion"}));
        items.add(new ItemAlias("Thick Potion", Material.POTION, (short)32, new String[] {"tpotion"}));
        items.add(new ItemAlias("Mundane Potion (Extended);", Material.POTION, (short)64, new String[] {"extendedmundanepotion", "mundanepotextended"}));
        items.add(new ItemAlias("Mundane Potion", Material.POTION, (short)8192, new String[] {"mundanepot"}));
        items.add(new ItemAlias("Potion of Regeneration", Material.POTION, (short)8193, new String[] {}));
        items.add(new ItemAlias("Potion of Regeneration (Extended);", Material.POTION, (short)8257, new String[] {}));
        items.add(new ItemAlias("Potion of Regeneration II", Material.POTION, (short)8225, new String[] {}));
        items.add(new ItemAlias("Potion of Swiftness", Material.POTION, (short)8194, new String[] {}));
        items.add(new ItemAlias("Potion of Swiftness (Extended);", Material.POTION, (short)8258, new String[] {}));
        items.add(new ItemAlias("Potion of Swiftness II", Material.POTION, (short)8226, new String[] {}));
        items.add(new ItemAlias("Potion of Fire Resistance", Material.POTION, (short)8195, new String[] {}));
        items.add(new ItemAlias("Potion of Fire Resistance (Extended);", Material.POTION, (short)8259, new String[] {}));
        items.add(new ItemAlias("Potion of Fire Resistance (Reverted);", Material.POTION, (short)8227, new String[] {}));
        items.add(new ItemAlias("Potion of Healing", Material.POTION, (short)8197, new String[] {}));
        items.add(new ItemAlias("Potion of Healing (Reverted);", Material.POTION, (short)8261, new String[] {}));
        items.add(new ItemAlias("Potion of Healing II", Material.POTION, (short)8229, new String[] {}));
        items.add(new ItemAlias("Potion of Strength", Material.POTION, (short)8201, new String[] {}));
        items.add(new ItemAlias("Potion of Strength (Extended);", Material.POTION, (short)8265, new String[] {}));
        items.add(new ItemAlias("Potion of Strength II", Material.POTION, (short)8233, new String[] {}));
        items.add(new ItemAlias("Potion of Poison", Material.POTION, (short)8196, new String[] {}));
        items.add(new ItemAlias("Potion of Poison (Extended);", Material.POTION, (short)8260, new String[] {}));
        items.add(new ItemAlias("Potion of Poison II", Material.POTION, (short)8228, new String[] {}));
        items.add(new ItemAlias("Potion of Weakness", Material.POTION, (short)8200, new String[] {}));
        items.add(new ItemAlias("Potion of Weakness (Extended);", Material.POTION, (short)8264, new String[] {}));
        items.add(new ItemAlias("Potion of Weakness (Reverted);", Material.POTION, (short)8232, new String[] {}));
        items.add(new ItemAlias("Potion of Slowness", Material.POTION, (short)8202, new String[] {}));
        items.add(new ItemAlias("Potion of Slowness (Extended);", Material.POTION, (short)8266, new String[] {}));
        items.add(new ItemAlias("Potion of Slowness (Reverted);", Material.POTION, (short)8234, new String[] {}));
        items.add(new ItemAlias("Potion of Harming", Material.POTION, (short)8204, new String[] {}));
        items.add(new ItemAlias("Potion of Harming (Reverted);", Material.POTION, (short)8268, new String[] {}));
        items.add(new ItemAlias("Potion of Harming II", Material.POTION, (short)8236, new String[] {}));
        items.add(new ItemAlias("Splash Mundane Potion", Material.POTION, (short)16384, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Regeneration", Material.POTION, (short)16385, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Regeneration (Extended);", Material.POTION, (short)16449, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Regeneration II", Material.POTION, (short)16417, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Swiftness", Material.POTION, (short)16386, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Swiftness (Extended);", Material.POTION, (short)16450, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Swiftness II", Material.POTION, (short)16418, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Fire Resistance", Material.POTION, (short)16387, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Fire Resistance (Extended);", Material.POTION, (short)16451, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Fire Resistance (Reverted);", Material.POTION, (short)16419, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Healing", Material.POTION, (short)16389, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Healing (Reverted);", Material.POTION, (short)16453, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Healing II", Material.POTION, (short)16421, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Strength", Material.POTION, (short)16393, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Strength (Extended);", Material.POTION, (short)16457, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Strength II", Material.POTION, (short)16425, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Poison", Material.POTION, (short)16388, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Poison (Extended);", Material.POTION, (short)16452, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Poison II", Material.POTION, (short)16420, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Weakness", Material.POTION, (short)16392, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Weakness (Extended);", Material.POTION, (short)16456, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Weakness (Reverted);", Material.POTION, (short)16424, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Slowness", Material.POTION, (short)16394, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Slowness (Extended);", Material.POTION, (short)16458, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Slowness (Reverted);", Material.POTION, (short)16426, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Harming", Material.POTION, (short)16396, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Harming (Reverted);", Material.POTION, (short)16460, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Harming II", Material.POTION, (short)16428, new String[] {}));
        items.add(new ItemAlias("Spider Eye", Material.SPIDER_EYE, (short)0, new String[] {"eye"}));
        items.add(new ItemAlias("Fermented Spider Eye", Material.FERMENTED_SPIDER_EYE, (short)0, new String[] {"fermentedeye"}));
        items.add(new ItemAlias("Blaze Powder", Material.BLAZE_POWDER, (short)0, new String[] {}));
        items.add(new ItemAlias("Magma Cream", Material.MAGMA_CREAM, (short)0, new String[] {"cream"}));
        items.add(new ItemAlias("Eye of Ender", Material.EYE_OF_ENDER, (short)0, new String[] {"endereye", "eeye"}));
        items.add(new ItemAlias("Glistering Melon", Material.SPECKLED_MELON, (short)0, new String[] {"glistermelon", "gmelon"}));
        items.add(new ItemAlias("Spawn Egg", Material.MONSTER_EGG, (short)0, new String[] {"spawn"}));
        items.add(new ItemAlias("Creeper Spawn Egg", Material.MONSTER_EGG, (short)50, new String[] {"spawncreeper", "creeperegg", "creepegg"}));
        items.add(new ItemAlias("Skeleton Spawn Egg", Material.MONSTER_EGG, (short)51, new String[] {"spawnskeleton", "spawnskelly", "skellyegg", "skelegg", "skeletonegg"}));
        items.add(new ItemAlias("Spider Spawn Egg", Material.MONSTER_EGG, (short)52, new String[] {"spideregg", "spawnspider"}));
        items.add(new ItemAlias("Zombie Spawn Egg", Material.MONSTER_EGG, (short)54, new String[] {"spawnzombie", "zombieegg"}));
        items.add(new ItemAlias("Slime Spawn Egg", Material.MONSTER_EGG, (short)55, new String[] {"slimeegg", "spawnslime"}));
        items.add(new ItemAlias("Ghast Spawn Egg", Material.MONSTER_EGG, (short)56, new String[] {"spawnghast", "ghastegg"}));
        items.add(new ItemAlias("Zombie Pigman Spawn Egg", Material.MONSTER_EGG, (short)57, new String[] {"pigmanegg", "spawnpigman", "zombiepigmanegg", "spawnzombiepigman"}));
        items.add(new ItemAlias("Enderman Spawn Egg", Material.MONSTER_EGG, (short)58, new String[] {"spawnenderman", "endermanegg"}));
        items.add(new ItemAlias("Cave Spider Spawn Egg", Material.MONSTER_EGG, (short)59, new String[] {"cavespideregg", "spawncavespider"}));
        items.add(new ItemAlias("Silverfish Spawn Egg", Material.MONSTER_EGG, (short)60, new String[] {"spawnsilverfish", "silverfishegg"}));
        items.add(new ItemAlias("Blaze Spawn Egg", Material.MONSTER_EGG, (short)61, new String[] {"spawnblaze", "blazeegg"}));
        items.add(new ItemAlias("Magma Cube Spawn Egg", Material.MONSTER_EGG, (short)62, new String[] {"spawnmagmacube", "magmacubeegg"}));
        items.add(new ItemAlias("Pig Spawn Egg", Material.MONSTER_EGG, (short)90, new String[] {"spawnpig", "pigegg"}));
        items.add(new ItemAlias("Sheep Spawn Egg", Material.MONSTER_EGG, (short)91, new String[] {"spawnsheep", "sheepegg"}));
        items.add(new ItemAlias("Cow Spawn Egg", Material.MONSTER_EGG, (short)92, new String[] {"spawncow", "cowegg"}));
        items.add(new ItemAlias("Chicken Spawn Egg", Material.MONSTER_EGG, (short)93, new String[] {"spawnchicken", "chickenegg", "spawnchick", "chickegg"}));
        items.add(new ItemAlias("Squid Spawn Egg", Material.MONSTER_EGG, (short)94, new String[] {"spawnsquid", "squidegg"}));
        items.add(new ItemAlias("Wolf Spawn Egg", Material.MONSTER_EGG, (short)95, new String[] {"spawnwolf", "wolfegg"}));
        items.add(new ItemAlias("Mooshroom Spawn Egg", Material.MONSTER_EGG, (short)96, new String[] {"spawnmooshroom", "mooshroomegg", "mushroomcowspawnegg", "mushroomcowegg", "spawnmushroomcow", "shroomcowegg", "spawnshroomcow", "shroomcowspawnegg"}));
        items.add(new ItemAlias("Ocelot Spawn Egg", Material.MONSTER_EGG, (short)98, new String[] {"spawnocelot", "spawncat", "ocelotegg", "categg"}));
        items.add(new ItemAlias("Villager Spawn Egg", Material.MONSTER_EGG, (short)120, new String[] {"spawnvillager", "villageregg"}));
        items.add(new ItemAlias("Bottle 'o Enchanting", Material.EXP_BOTTLE, (short)0, new String[] {"xpbottle", "expbottle", "bottleoenchanting"}));
        items.add(new ItemAlias("Fire Charge", Material.FIREBALL, (short)0, new String[] {"firecharge"}));
        items.add(new ItemAlias("13 Disc", Material.GOLD_RECORD, (short)0, new String[] {}));
        items.add(new ItemAlias("cat Disc", Material.GREEN_RECORD, (short)0, new String[] {}));
        items.add(new ItemAlias("blocks Disc", Material.RECORD_3, (short)0, new String[] {}));
        items.add(new ItemAlias("chirp Disc", Material.RECORD_4, (short)0, new String[] {}));
        items.add(new ItemAlias("far Disc", Material.RECORD_5, (short)0, new String[] {}));
        items.add(new ItemAlias("mall Disc", Material.RECORD_6, (short)0, new String[] {}));
        items.add(new ItemAlias("mellohi Disc", Material.RECORD_7, (short)0, new String[] {}));
        items.add(new ItemAlias("stahl Disc", Material.RECORD_8, (short)0, new String[] {}));
        items.add(new ItemAlias("strad Disc", Material.RECORD_9, (short)0, new String[] {}));
        items.add(new ItemAlias("ward Disc", Material.RECORD_10, (short)0, new String[] {}));
        items.add(new ItemAlias("11 Disc", Material.RECORD_11, (short)0, new String[] {}));
        items.add(new ItemAlias("wait Disc", Material.RECORD_12, (short)0, new String[] {}));
        items.add(new ItemAlias("Redstone Lamp", Material.REDSTONE_LAMP_OFF, (short)0, new String[] {}));
        items.add(new ItemAlias("Redstone Torch Off", Material.REDSTONE_TORCH_OFF, (short)0, new String[] {}));
        items.add(new ItemAlias("Emerald Ore", Material.EMERALD_ORE, (short)0, new String[] {}));
        items.add(new ItemAlias("Emerald", Material.EMERALD, (short)0, new String[] {}));
        items.add(new ItemAlias("Emerald Block", Material.EMERALD_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Ender Chest", Material.ENDER_CHEST, (short)0, new String[] {}));
        items.add(new ItemAlias("Tripwire Hook", Material.TRIPWIRE_HOOK, (short)0, new String[] {}));
        items.add(new ItemAlias("Tripwire", Material.TRIPWIRE, (short)0, new String[] {}));
        items.add(new ItemAlias("Sandstone Stair", Material.SANDSTONE_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Double Oak Slab", Material.WOOD_DOUBLE_STEP, (short)0, new String[] {}));
        items.add(new ItemAlias("Double Spruce Slab", Material.WOOD_DOUBLE_STEP, (short)1, new String[] {}));
        items.add(new ItemAlias("Double Birch Slab", Material.WOOD_DOUBLE_STEP, (short)2, new String[] {}));
        items.add(new ItemAlias("Double Jungle Wood Slab", Material.WOOD_DOUBLE_STEP, (short)3, new String[] {}));
        items.add(new ItemAlias("Oak Slab", Material.WOOD_STEP, (short)0, new String[] {}));
        items.add(new ItemAlias("Spruce Slab", Material.WOOD_STEP, (short)1, new String[] {}));
        items.add(new ItemAlias("Birch Slab", Material.WOOD_STEP, (short)2, new String[] {}));
        items.add(new ItemAlias("Jungle Wood Slab", Material.WOOD_STEP, (short)3, new String[] {}));
        items.add(new ItemAlias("Book and Quill", Material.BOOK_AND_QUILL, (short)0, new String[] {}));
        items.add(new ItemAlias("Written Book", Material.WRITTEN_BOOK, (short)0, new String[] {}));
        items.add(new ItemAlias("Cocoa Pod", Material.COCOA, (short)0, new String[] {}));
        items.add(new ItemAlias("Command Block", Material.COMMAND, (short)0, new String[] {}));
        items.add(new ItemAlias("Beacon Block", Material.BEACON, (short)0, new String[] {}));
        items.add(new ItemAlias("Anvil", Material.ANVIL, (short)0, new String[] {}));
        items.add(new ItemAlias("Slightly Damaged Anvil", Material.ANVIL, (short)1, new String[] {}));
        items.add(new ItemAlias("Very Damaged Anvil", Material.ANVIL, (short)2, new String[] {}));
        items.add(new ItemAlias("Flower Pot Block", Material.FLOWER_POT, (short)0, new String[] {}));
        items.add(new ItemAlias("Flower Pot", Material.FLOWER_POT_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Cobblestone Wall", Material.COBBLE_WALL, (short)0, new String[] {}));
        items.add(new ItemAlias("Mossy Cobblestone Wall", Material.COBBLE_WALL, (short)1, new String[] {}));
        items.add(new ItemAlias("Item Frame", Material.ITEM_FRAME, (short)0, new String[] {}));
        items.add(new ItemAlias("Skeleton Skull", Material.SKULL_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Wither Skeleton Skull", Material.SKULL_ITEM, (short)1, new String[] {}));
        items.add(new ItemAlias("Zombie Head", Material.SKULL_ITEM, (short)2, new String[] {}));
        items.add(new ItemAlias("Human Head", Material.SKULL_ITEM, (short)3, new String[] {}));
        items.add(new ItemAlias("Creeper Head", Material.SKULL_ITEM, (short)4, new String[] {}));
        items.add(new ItemAlias("Carrot", Material.CARROT_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Golden Carrot", Material.GOLDEN_CARROT, (short)0, new String[] {}));
        items.add(new ItemAlias("Carrot Block", Material.CARROT, (short)0, new String[] {}));
        items.add(new ItemAlias("Carrot on a Stick", Material.CARROT_STICK, (short)0, new String[] {}));
        items.add(new ItemAlias("Potato", Material.POTATO_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Potato Block", Material.POTATO, (short)0, new String[] {}));
        items.add(new ItemAlias("Baked Potato", Material.BAKED_POTATO, (short)0, new String[] {}));
        items.add(new ItemAlias("Poisonous Potato", Material.POISONOUS_POTATO, (short)0, new String[] {}));
        items.add(new ItemAlias("Wood Button", Material.WOOD_BUTTON, (short)0, new String[] {}));
        items.add(new ItemAlias("Pumpkin Pie", Material.PUMPKIN_PIE, (short)0, new String[] {}));
        items.add(new ItemAlias("Potion of Invisibility", Material.POTION, (short)8206, new String[] {}));
        items.add(new ItemAlias("Potion of Invisibility (Extended);", Material.POTION, (short)8270, new String[] {}));
        items.add(new ItemAlias("Potion of Night Vision", Material.POTION, (short)8198, new String[] {}));
        items.add(new ItemAlias("Potion of Night Vision (Extended);", Material.POTION, (short)8262, new String[] {}));
        items.add(new ItemAlias("Enchanted Book", Material.ENCHANTED_BOOK, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Star", Material.NETHER_STAR, (short)0, new String[] {}));
        items.add(new ItemAlias("Firework Star", Material.FIREWORK_CHARGE, (short)0, new String[] {}));
        items.add(new ItemAlias("Firework Rocket", Material.FIREWORK, (short)0, new String[] {}));
        items.add(new ItemAlias("White Firework Star", Material.FIREWORK_CHARGE, (short)1, new String[] {}));
        items.add(new ItemAlias("Orange Firework Star", Material.FIREWORK_CHARGE, (short)2, new String[] {}));
        items.add(new ItemAlias("Magenta Firework Star", Material.FIREWORK_CHARGE, (short)3, new String[] {}));
        items.add(new ItemAlias("Light Blue Firework Star", Material.FIREWORK_CHARGE, (short)4, new String[] {}));
        items.add(new ItemAlias("Yellow Firework Star", Material.FIREWORK_CHARGE, (short)5, new String[] {}));
        items.add(new ItemAlias("Lime Firework Star", Material.FIREWORK_CHARGE, (short)6, new String[] {}));
        items.add(new ItemAlias("Pink Firework Star", Material.FIREWORK_CHARGE, (short)7, new String[] {}));
        items.add(new ItemAlias("Gray Firework Star", Material.FIREWORK_CHARGE, (short)8, new String[] {}));
        items.add(new ItemAlias("Light Gray Firework Star", Material.FIREWORK_CHARGE, (short)9, new String[] {}));
        items.add(new ItemAlias("Cyan Firework Star", Material.FIREWORK_CHARGE, (short)10, new String[] {}));
        items.add(new ItemAlias("Purple Firework Star", Material.FIREWORK_CHARGE, (short)11, new String[] {}));
        items.add(new ItemAlias("Blue Firework Star", Material.FIREWORK_CHARGE, (short)12, new String[] {}));
        items.add(new ItemAlias("Brown Firework Star", Material.FIREWORK_CHARGE, (short)13, new String[] {}));
        items.add(new ItemAlias("Green Firework Star", Material.FIREWORK_CHARGE, (short)14, new String[] {}));
        items.add(new ItemAlias("Red Firework Star", Material.FIREWORK_CHARGE, (short)15, new String[] {}));
        items.add(new ItemAlias("Black Firework Star", Material.FIREWORK_CHARGE, (short)16, new String[] {}));
        items.add(new ItemAlias("Dead Bush", Material.DEAD_BUSH, (short)0, new String[] {"deadbush", "dbush", "bush"}));
        items.add(new ItemAlias("Nether Brick Slab", Material.STEP, (short)6, new String[] {}));
        items.add(new ItemAlias("Activator Rail", Material.ACTIVATOR_RAIL, (short)0, new String[] {}));
        items.add(new ItemAlias("Block of Redstone", Material.REDSTONE_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Daylight Sensor", Material.DAYLIGHT_DETECTOR, (short)0, new String[] {}));
        items.add(new ItemAlias("Dropper", Material.DROPPER, (short)0, new String[] {}));
        items.add(new ItemAlias("Hopper", Material.HOPPER, (short)0, new String[] {}));
        items.add(new ItemAlias("Explosive Minecart", Material.EXPLOSIVE_MINECART, (short)0, new String[] {}));
        items.add(new ItemAlias("Hopper Minecart", Material.HOPPER_MINECART, (short)0, new String[] {}));
        items.add(new ItemAlias("Redstone Comparator", Material.REDSTONE_COMPARATOR, (short)0, new String[] {}));
        items.add(new ItemAlias("Trapped Chest", Material.TRAPPED_CHEST, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Brick Item", Material.NETHER_BRICK_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Quartz", Material.QUARTZ, (short)0, new String[] {}));
        items.add(new ItemAlias("Nether Quartz Ore", Material.QUARTZ_ORE, (short)0, new String[] {}));
        items.add(new ItemAlias("Quartz Block", Material.QUARTZ_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Quartz Slab", Material.STEP, (short)7, new String[] {}));
        items.add(new ItemAlias("Quartz Double Slab", Material.DOUBLE_STEP, (short)7, new String[] {}));
        items.add(new ItemAlias("Quartz Stairs", Material.QUARTZ_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Chiseled Quartz", Material.QUARTZ_BLOCK, (short)1, new String[] {}));
        items.add(new ItemAlias("Quartz Pillar", Material.QUARTZ_BLOCK, (short)2, new String[] {}));
        items.add(new ItemAlias("Weighted Gold Plate", Material.GOLD_PLATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Weighted Iron Plate", Material.IRON_PLATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Horse Spawn Egg", Material.MONSTER_EGG, (short)100, new String[] {}));
        items.add(new ItemAlias("Diamond Horse Armor", Material.DIAMOND_BARDING, (short)0, new String[] {}));
        items.add(new ItemAlias("Gold Horse Armor", Material.GOLD_BARDING, (short)0, new String[] {}));
        items.add(new ItemAlias("Iron Horse Armor", Material.IRON_BARDING, (short)0, new String[] {}));
        items.add(new ItemAlias("Leash", Material.LEASH, (short)0, new String[] {}));
        items.add(new ItemAlias("Hay Bale", Material.HAY_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Name Tag", Material.NAME_TAG, (short)0, new String[] {}));
        items.add(new ItemAlias("Hardened Clay", Material.HARD_CLAY, (short)0, new String[] {}));
        items.add(new ItemAlias("Block of Coal", Material.COAL_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("White Stained Clay", Material.STAINED_CLAY, (short)0, new String[] {}));
        items.add(new ItemAlias("Orange Stained Clay", Material.STAINED_CLAY, (short)1, new String[] {}));
        items.add(new ItemAlias("Magenta Stained Clay", Material.STAINED_CLAY, (short)2, new String[] {}));
        items.add(new ItemAlias("Light Blue Stained Clay", Material.STAINED_CLAY, (short)3, new String[] {}));
        items.add(new ItemAlias("Yellow Stained Clay", Material.STAINED_CLAY, (short)4, new String[] {}));
        items.add(new ItemAlias("Lime Stained Clay", Material.STAINED_CLAY, (short)5, new String[] {}));
        items.add(new ItemAlias("Pink Stained Clay", Material.STAINED_CLAY, (short)6, new String[] {}));
        items.add(new ItemAlias("Gray Stained Clay", Material.STAINED_CLAY, (short)7, new String[] {}));
        items.add(new ItemAlias("Light Gray Stained Clay", Material.STAINED_CLAY, (short)8, new String[] {}));
        items.add(new ItemAlias("Cyan Stained Clay", Material.STAINED_CLAY, (short)9, new String[] {}));
        items.add(new ItemAlias("Purple Stained Clay", Material.STAINED_CLAY, (short)10, new String[] {}));
        items.add(new ItemAlias("Blue Stained Clay", Material.STAINED_CLAY, (short)11, new String[] {}));
        items.add(new ItemAlias("Brown Stained Clay", Material.STAINED_CLAY, (short)12, new String[] {}));
        items.add(new ItemAlias("Green Stained Clay", Material.STAINED_CLAY, (short)13, new String[] {}));
        items.add(new ItemAlias("Red Stained Clay", Material.STAINED_CLAY, (short)14, new String[] {}));
        items.add(new ItemAlias("Black Stained Clay", Material.STAINED_CLAY, (short)15, new String[] {}));
        items.add(new ItemAlias("White Carpet", Material.CARPET, (short)0, new String[] {}));
        items.add(new ItemAlias("Orange Carpet", Material.CARPET, (short)1, new String[] {}));
        items.add(new ItemAlias("Magenta Carpet", Material.CARPET, (short)2, new String[] {}));
        items.add(new ItemAlias("Light Blue Carpet", Material.CARPET, (short)3, new String[] {}));
        items.add(new ItemAlias("Yellow Carpet", Material.CARPET, (short)4, new String[] {}));
        items.add(new ItemAlias("Light Green Carpet", Material.CARPET, (short)5, new String[] {}));
        items.add(new ItemAlias("Pink Carpet", Material.CARPET, (short)6, new String[] {}));
        items.add(new ItemAlias("Gray Carpet", Material.CARPET, (short)7, new String[] {}));
        items.add(new ItemAlias("Light Gray Carpet", Material.CARPET, (short)8, new String[] {}));
        items.add(new ItemAlias("Cyan Carpet", Material.CARPET, (short)9, new String[] {}));
        items.add(new ItemAlias("Purple Carpet", Material.CARPET, (short)10, new String[] {}));
        items.add(new ItemAlias("Blue Carpet", Material.CARPET, (short)11, new String[] {}));
        items.add(new ItemAlias("Brown Carpet", Material.CARPET, (short)12, new String[] {}));
        items.add(new ItemAlias("Dark Green Carpet", Material.CARPET, (short)13, new String[] {}));
        items.add(new ItemAlias("Red Carpet", Material.CARPET, (short)14, new String[] {}));
        items.add(new ItemAlias("Black Carpet", Material.CARPET, (short)15, new String[] {}));
        items.add(new ItemAlias("Packed Ice", Material.PACKED_ICE, (short)0, new String[] {}));
        items.add(new ItemAlias("Coarse Dirt", Material.DIRT, (short)1, new String[] {}));
        items.add(new ItemAlias("Acacia Log", Material.LOG_2, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Log", Material.LOG_2, (short)1, new String[] {}));
        items.add(new ItemAlias("Acacia Plank", Material.WOOD, (short)4, new String[] {"aplank"}));
        items.add(new ItemAlias("Dark Oak Plank", Material.WOOD, (short)5, new String[] {"doplank"}));
        items.add(new ItemAlias("Acacia Wood Stairs", Material.ACACIA_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Wood Stairs", Material.DARK_OAK_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Acacia Sapling", Material.SAPLING, (short)4, new String[] {}));
        items.add(new ItemAlias("Dark Oak Sapling", Material.SAPLING, (short)5, new String[] {}));
        items.add(new ItemAlias("Acacia Leaves", Material.LEAVES_2, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Leaves", Material.LEAVES_2, (short)1, new String[] {}));
        items.add(new ItemAlias("Packed Ice", Material.PACKED_ICE, (short)0, new String[] {}));
        items.add(new ItemAlias("Podzol", Material.DIRT, (short)2, new String[] {}));
        items.add(new ItemAlias("Red Sand", Material.SAND, (short)1, new String[] {}));
        items.add(new ItemAlias("Cobblestone Monster Egg", Material.MONSTER_EGGS, (short)1, new String[] {}));
        items.add(new ItemAlias("Cracked Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)4, new String[] {}));
        items.add(new ItemAlias("Chiseled Stone Brick Monster Egg", Material.MONSTER_EGGS, (short)5, new String[] {}));
        items.add(new ItemAlias("White Stained Glass", Material.STAINED_GLASS, (short)0, new String[] {}));
        items.add(new ItemAlias("Orange Stained Glass", Material.STAINED_GLASS, (short)1, new String[] {}));
        items.add(new ItemAlias("Magenta Stained Glass", Material.STAINED_GLASS, (short)2, new String[] {}));
        items.add(new ItemAlias("Light Blue Stained Glass", Material.STAINED_GLASS, (short)3, new String[] {}));
        items.add(new ItemAlias("Yellow Stained Glass", Material.STAINED_GLASS, (short)4, new String[] {}));
        items.add(new ItemAlias("Light Green Stained Glass", Material.STAINED_GLASS, (short)5, new String[] {}));
        items.add(new ItemAlias("Pink Stained Glass", Material.STAINED_GLASS, (short)6, new String[] {}));
        items.add(new ItemAlias("Gray Stained Glass", Material.STAINED_GLASS, (short)7, new String[] {}));
        items.add(new ItemAlias("Light Gray Stained Glass", Material.STAINED_GLASS, (short)8, new String[] {}));
        items.add(new ItemAlias("Cyan Stained Glass", Material.STAINED_GLASS, (short)9, new String[] {}));
        items.add(new ItemAlias("Purple Stained Glass", Material.STAINED_GLASS, (short)10, new String[] {}));
        items.add(new ItemAlias("Blue Stained Glass", Material.STAINED_GLASS, (short)11, new String[] {}));
        items.add(new ItemAlias("Brown Stained Glass", Material.STAINED_GLASS, (short)12, new String[] {}));
        items.add(new ItemAlias("Dark Green Stained Glass", Material.STAINED_GLASS, (short)13, new String[] {}));
        items.add(new ItemAlias("Red Stained Glass", Material.STAINED_GLASS, (short)14, new String[] {}));
        items.add(new ItemAlias("Black Stained Glass", Material.STAINED_GLASS, (short)15, new String[] {}));
        items.add(new ItemAlias("White Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)0, new String[] {}));
        items.add(new ItemAlias("Orange Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)1, new String[] {}));
        items.add(new ItemAlias("Magenta Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)2, new String[] {}));
        items.add(new ItemAlias("Light Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)3, new String[] {}));
        items.add(new ItemAlias("Yellow Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)4, new String[] {}));
        items.add(new ItemAlias("Light Green Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)5, new String[] {}));
        items.add(new ItemAlias("Pink Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)6, new String[] {}));
        items.add(new ItemAlias("Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)7, new String[] {}));
        items.add(new ItemAlias("Light Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)8, new String[] {}));
        items.add(new ItemAlias("Cyan Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)9, new String[] {}));
        items.add(new ItemAlias("Purple Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)10, new String[] {}));
        items.add(new ItemAlias("Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)11, new String[] {}));
        items.add(new ItemAlias("Brown Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)12, new String[] {}));
        items.add(new ItemAlias("Dark Green Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)13, new String[] {}));
        items.add(new ItemAlias("Red Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)14, new String[] {}));
        items.add(new ItemAlias("Black Stained Glass Pane", Material.STAINED_GLASS_PANE, (short)15, new String[] {}));
        items.add(new ItemAlias("Poppy", Material.RED_ROSE, (short)0, new String[] {}));
        items.add(new ItemAlias("Blue Orchid", Material.RED_ROSE, (short)1, new String[] {}));
        items.add(new ItemAlias("Allium", Material.RED_ROSE, (short)2, new String[] {}));
        items.add(new ItemAlias("Azure Bluet", Material.RED_ROSE, (short)3, new String[] {}));
        items.add(new ItemAlias("Red Tulip", Material.RED_ROSE, (short)4, new String[] {}));
        items.add(new ItemAlias("Orange Tulip", Material.RED_ROSE, (short)5, new String[] {}));
        items.add(new ItemAlias("White Tulip", Material.RED_ROSE, (short)6, new String[] {}));
        items.add(new ItemAlias("Pink Tulip", Material.RED_ROSE, (short)7, new String[] {}));
        items.add(new ItemAlias("Oxeye Daisy", Material.RED_ROSE, (short)8, new String[] {}));
        items.add(new ItemAlias("Sunflower", Material.DOUBLE_PLANT, (short)0, new String[] {}));
        items.add(new ItemAlias("Lilac", Material.DOUBLE_PLANT, (short)1, new String[] {}));
        items.add(new ItemAlias("Double Tallgrass", Material.DOUBLE_PLANT, (short)2, new String[] {}));
        items.add(new ItemAlias("Large Fern", Material.DOUBLE_PLANT, (short)3, new String[] {}));
        items.add(new ItemAlias("Rose Bush", Material.DOUBLE_PLANT, (short)4, new String[] {}));
        items.add(new ItemAlias("Peony", Material.DOUBLE_PLANT, (short)5, new String[] {}));
        items.add(new ItemAlias("Command Minecart", Material.COMMAND_MINECART, (short)0, new String[] {"cmdminecart", "commandcart", "cmdcart"}));
        items.add(new ItemAlias("Potion of Water Breathing", Material.POTION, (short)8205, new String[] {}));
        items.add(new ItemAlias("Potion of Water Breathing (Reverted);", Material.POTION, (short)8237, new String[] {}));
        items.add(new ItemAlias("Potion of Water Breathing (Extended);", Material.POTION, (short)8269, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Water Breathing", Material.POTION, (short)16397, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Water Breathing (Reverted);", Material.POTION, (short)16429, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Water Breathing (Extended);", Material.POTION, (short)16461, new String[] {}));
        items.add(new ItemAlias("Raw Salmon", Material.RAW_FISH, (short)1, new String[] {}));
        items.add(new ItemAlias("Cooked Salmon", Material.COOKED_FISH, (short)1, new String[] {}));
        items.add(new ItemAlias("Clownfish", Material.RAW_FISH, (short)2, new String[] {}));
        items.add(new ItemAlias("Pufferfish", Material.RAW_FISH, (short)3, new String[] {}));
        items.add(new ItemAlias("Acacia Slab", Material.WOOD_STEP, (short)4, new String[] {}));
        items.add(new ItemAlias("Dark Oak Slab", Material.WOOD_STEP, (short)5, new String[] {}));
        items.add(new ItemAlias("Granite", Material.STONE, (short)1, new String[] {}));
        items.add(new ItemAlias("Polished Granite", Material.STONE, (short)2, new String[] {}));
        items.add(new ItemAlias("Diorite", Material.STONE, (short)3, new String[] {}));
        items.add(new ItemAlias("Polished Diorite", Material.STONE, (short)4, new String[] {}));
        items.add(new ItemAlias("Andesite", Material.STONE, (short)5, new String[] {}));
        items.add(new ItemAlias("Polished Andesite", Material.STONE, (short)6, new String[] {}));
        items.add(new ItemAlias("Slime Block", Material.SLIME_BLOCK, (short)0, new String[] {}));
        items.add(new ItemAlias("Wet Sponge", Material.SPONGE, (short)1, new String[] {}));
        items.add(new ItemAlias("Barrier", Material.BARRIER, (short)0, new String[] {}));
        items.add(new ItemAlias("Iron Trapdoor", Material.IRON_TRAPDOOR, (short)0, new String[] {}));
        items.add(new ItemAlias("Prismarine", Material.PRISMARINE, (short)0, new String[] {}));
        items.add(new ItemAlias("Prismarine Bricks", Material.PRISMARINE, (short)1, new String[] {}));
        items.add(new ItemAlias("Dark Prismarine", Material.PRISMARINE, (short)2, new String[] {}));
        items.add(new ItemAlias("Sea Lantern", Material.SEA_LANTERN, (short)0, new String[] {}));
        items.add(new ItemAlias("Red Sandstone", Material.RED_SANDSTONE, (short)0, new String[] {}));
        items.add(new ItemAlias("Chiseled Red Sandstone", Material.RED_SANDSTONE, (short)1, new String[] {}));
        items.add(new ItemAlias("Smooth Red Sandstone", Material.RED_SANDSTONE, (short)2, new String[] {}));
        items.add(new ItemAlias("Red Sandstone Stairs", Material.RED_SANDSTONE_STAIRS, (short)0, new String[] {}));
        items.add(new ItemAlias("Red Sandstone Slab", Material.STONE_SLAB2, (short)0, new String[] {}));
        items.add(new ItemAlias("Spruce Fence Gate", Material.SPRUCE_FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Birch Fence Gate", Material.BIRCH_FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Jungle Fence Gate", Material.JUNGLE_FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Fence Gate", Material.DARK_OAK_FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Acacia Fence Gate", Material.ACACIA_FENCE_GATE, (short)0, new String[] {}));
        items.add(new ItemAlias("Spruce Fence", Material.SPRUCE_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Birch Fence", Material.BIRCH_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Jungle Fence", Material.JUNGLE_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Fence", Material.DARK_OAK_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Acacia Fence", Material.ACACIA_FENCE, (short)0, new String[] {}));
        items.add(new ItemAlias("Spruce Door", Material.SPRUCE_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Birch Door", Material.BIRCH_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Jungle Door", Material.JUNGLE_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Dark Oak Door", Material.DARK_OAK_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Acacia Door", Material.ACACIA_DOOR_ITEM, (short)0, new String[] {}));
        items.add(new ItemAlias("Prismarine Shard", Material.PRISMARINE_SHARD, (short)0, new String[] {}));
        items.add(new ItemAlias("Prismarine Crystal", Material.PRISMARINE_CRYSTALS, (short)0, new String[] {}));
        items.add(new ItemAlias("Raw Rabbit", Material.RABBIT, (short)0, new String[] {}));
        items.add(new ItemAlias("Cooked Rabbit", Material.COOKED_RABBIT, (short)0, new String[] {}));
        items.add(new ItemAlias("Rabbit Stew", Material.RABBIT_STEW, (short)0, new String[] {}));
        items.add(new ItemAlias("Rabbit Foot", Material.RABBIT_FOOT, (short)0, new String[] {}));
        items.add(new ItemAlias("Rabbit Hide", Material.RABBIT_HIDE, (short)0, new String[] {}));
        items.add(new ItemAlias("Armor Stand", Material.ARMOR_STAND, (short)0, new String[] {}));
        items.add(new ItemAlias("Raw Mutton", Material.MUTTON, (short)0, new String[] {}));
        items.add(new ItemAlias("Cooked Mutton", Material.COOKED_MUTTON, (short)0, new String[] {}));
        items.add(new ItemAlias("White Banner", Material.BANNER, (short)15, new String[] {}));
        items.add(new ItemAlias("Orange Banner", Material.BANNER, (short)14, new String[] {}));
        items.add(new ItemAlias("Magenta Banner", Material.BANNER, (short)13, new String[] {}));
        items.add(new ItemAlias("Light Blue Banner", Material.BANNER, (short)12, new String[] {}));
        items.add(new ItemAlias("Yellow Banner", Material.BANNER, (short)11, new String[] {}));
        items.add(new ItemAlias("Lime Banner", Material.BANNER, (short)10, new String[] {}));
        items.add(new ItemAlias("Pink Banner", Material.BANNER, (short)9, new String[] {}));
        items.add(new ItemAlias("Gray Banner", Material.BANNER, (short)8, new String[] {}));
        items.add(new ItemAlias("Light Gray Banner", Material.BANNER, (short)7, new String[] {}));
        items.add(new ItemAlias("Cyan Banner", Material.BANNER, (short)6, new String[] {}));
        items.add(new ItemAlias("Purple Banner", Material.BANNER, (short)5, new String[] {}));
        items.add(new ItemAlias("Blue Banner", Material.BANNER, (short)4, new String[] {}));
        items.add(new ItemAlias("Brown Banner", Material.BANNER, (short)3, new String[] {}));
        items.add(new ItemAlias("Green Banner", Material.BANNER, (short)2, new String[] {}));
        items.add(new ItemAlias("Red Banner", Material.BANNER, (short)1, new String[] {}));
        items.add(new ItemAlias("Black Banner", Material.BANNER, (short)0, new String[] {}));
        items.add(new ItemAlias("Potion of Leaping", Material.POTION, (short)8203, new String[] {}));
        items.add(new ItemAlias("Potion of Leaping (Extended);", Material.POTION, (short)8267, new String[] {}));
        items.add(new ItemAlias("Potion of Leaping II", Material.POTION, (short)8235, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Leaping", Material.POTION, (short)16395, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Leaping (Extended);", Material.POTION, (short)16459, new String[] {}));
        items.add(new ItemAlias("Splash Potion of Leaping II", Material.POTION, (short)16427, new String[] {}));
        items.add(new ItemAlias("Bat Spawn Egg", Material.MONSTER_EGG, (short)65, new String[] {}));
        items.add(new ItemAlias("Witch Spawn Egg", Material.MONSTER_EGG, (short)66, new String[] {}));
        items.add(new ItemAlias("Endermite Spawn Egg", Material.MONSTER_EGG, (short)67, new String[] {}));
        items.add(new ItemAlias("Guardian Spawn Egg", Material.MONSTER_EGG, (short)68, new String[] {}));
        items.add(new ItemAlias("Rabbit Spawn Egg", Material.MONSTER_EGG, (short)101, new String[] {}));

        for (ItemAlias item : items) {
            itemLookup.put(item.getKey(), item);
        }
    }

}
