main : ${project.groupId}.essencecore.EssenceCore
name: EssenceCore
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: ${project.author}
authors: ${project.authors}
softdepend: [Vault]